// Customer Config for the node graph — the LEGACY page, with graph rules under it.
//
// The layout, the class names and the element sizes are a 1-1 copy of
// design/customerSection.ts: the same `.level-params-bar`, the same estimate
// bar and chart foldout, the same `.customer-cards` row with Sortable
// reordering and a trailing add-card, the same `.customer-head` with its wait
// badge and weather toggle, and the same `.dish-row` / `.dish-chips` /
// `.chip icon-chip dish-chip` at 64px. A designer moving between the two tabs
// should not be able to tell them apart by looking.
//
// What changes is underneath, and it shows up in exactly one place a designer
// can see: RIGHT-CLICKING A DISH opens a menu that configures that dish's
// nested composite and groups. A legacy dish is a flat bag of cooked ids, so
// its dish menu had nothing structural to offer; a node dish is a bracket tree,
// so that menu is where the tree is edited.
//
// The chips themselves stay flat, in resolved slot order (base first). Chip
// gestures are the legacy ones, narrowed to what the graph allows: `＋` offers
// options grouped by slot, and right-clicking a chip swaps it within its own
// slot rather than across every cooked ingredient in the map.

import Sortable from "sortablejs";
import { CUSTOMER_STAFF } from "../../core/effects.ts";
import { parseNodeCustomers, serializeNodeCustomers } from "../../core/nodeParser.ts";
import type { DishNode, NodeCustomerConfig, NodeDish } from "../../core/nodeParser.ts";
import type { GraphIndex, IndexedSlot } from "../../core/nodeIndex.ts";
import { describeIssue, orderIdIndex, resolveOrder } from "../../core/nodeOrder.ts";
import type { ElementDef, GlobalDefs } from "../../core/types.ts";
import type { IdIndex } from "../../data/nodeIdTable.ts";
import type { LevelData } from "../../data/mapLoader.ts";
import {
  addPickerGrid,
  closeContextMenu,
  importField,
  showContextContent,
  showContextMenu,
} from "../contextMenu.ts";
import type { MenuItem } from "../contextMenu.ts";
import { button, el } from "../dom.ts";
import { cookedIconEl } from "../icon.ts";
import { DEFAULT_MAX_DISH_SLOTS, parseDishCountSequence, serializeDishCountSequence } from "../design/autoGenerate.ts";
import { dishCountEditor } from "../design/autoGenerateDialog.ts";
import { defaultCurve, openCurveDialog, parseCurve, serializeCurve } from "../design/curveEditor.ts";
import { customerColor } from "../design/customerColors.ts";
import { difficultyColor, difficultyRatio } from "../design/estimateDifficulty.ts";
import type { EstimateResult } from "../design/estimateDifficulty.ts";
import { occupancyChartEl } from "../design/occupancyChart.ts";
import type { ChartVisibility } from "../design/occupancyChart.ts";
import {
  DEFAULT_INGREDIENT_WEIGHT,
  openIngredientWeightsDialog,
  parseIngredientWeights,
  serializeIngredientWeights,
} from "../design/ingredientWeightEditor.ts";
import { Section } from "../design/section.ts";
import type { ProjectedMap } from "../../data/nodeGraphToMapDef.ts";

/** Foldout-open flag plus the per-category legend toggles — see occupancyChart.ts. */
type ChartUi = { open: boolean } & ChartVisibility;

export interface NodeCustomerSectionDeps {
  ix: GraphIndex;
  projected: ProjectedMap;
  defs: GlobalDefs;
  level: LevelData;
  onSaved(): void;
  onCommit?(): void;
  onEstimate?(): void;
  currentEstimate?(): EstimateResult | null;
  onAutoGenerate?(): void;
}

const isStaff = (c: NodeCustomerConfig) => c.typeId === CUSTOMER_STAFF;

function typeDef(defs: GlobalDefs, typeId: number): ElementDef | undefined {
  return defs.customerTypes.find((t) => t.id === typeId);
}

export function createNodeCustomerSection(deps: NodeCustomerSectionDeps): Section<NodeCustomerConfig[]> {
  const ids: IdIndex = orderIdIndex(deps.ix);
  const chartUi: ChartUi = { open: false, scoredTint: true, randomTint: true, completeLines: true };

  const section: Section<NodeCustomerConfig[]> = new Section<NodeCustomerConfig[]>({
    title: "Customers",
    saveLabel: "Save Customers",
    initial: parseSafely(deps.level.customerString),
    renderBody: (draft, body) => renderBody(section, deps, ids, draft, body, chartUi),
    onCommit: () => deps.onCommit?.(),
    save: (draft) => {
      deps.level.customerString = serializeNodeCustomers(draft);
      deps.onSaved();
    },
    stringPreview: (draft) => serializeNodeCustomers(draft),
    headerButtons: () => [
      button("✨ Auto Generate", () => deps.onAutoGenerate?.(), {
        title: "Generate a customer sequence from a dish-count list, ingredient weights, and a complexity curve",
      }),
      button("📊 Estimate Difficulty", () => deps.onEstimate?.(), {
        title:
          "Play the level with a solver and report, per customer, how much grid space their order takes and how much is wasted. Also numbers each queue tile in pickup order.",
      }),
    ],
    menuItems: (draft) => [
      {
        label: "Import from string…",
        expand: (close) =>
          importField("typeId;waitTime;weatherEff;{c0:100.{g0:101}}|...", (text) => {
            const parsed = parseNodeCustomers(text);
            const added = parsed.length;
            const removed = draft.length;
            draft.length = 0;
            draft.push(...parsed);
            section.commit("Import customers from string", added, removed);
            close();
          }),
      },
      {
        label: "Clear All",
        danger: true,
        separator: true,
        onSelect: () => {
          if (!confirm("Remove every customer from this level?")) return;
          const removed = draft.length;
          draft.length = 0;
          section.commit("Clear all customers", 0, removed);
        },
      },
    ],
  });
  section.render();
  return section;
}

/** A malformed stored string must open the editor, not blank the page. */
function parseSafely(text: string): NodeCustomerConfig[] {
  try {
    return parseNodeCustomers(text);
  } catch (err) {
    console.warn("Customer string could not be parsed — starting empty", err);
    return [];
  }
}

// ---------- the dish tree ----------

/** How many members a slot holds: a fixed slot one, a group its cap (-1 = unlimited). */
export function slotCapacity(slot: IndexedSlot): number {
  if (slot.kind === "fixed") return 1;
  return slot.maxQuantity < 0 ? Number.POSITIVE_INFINITY : Math.max(1, slot.maxQuantity);
}

const orderableOf = (ix: GraphIndex, ids: IdIndex, dish: NodeDish): number => {
  const name = ids.byId.composite.get(dish.root.id);
  return name === undefined ? -1 : (ix.compositeByName.get(name) ?? -1);
};

/** The bracket a slot's members live in — the root for a fixed slot, a `{gN:…}` for a group. */
function containerFor(
  ids: IdIndex,
  ix: GraphIndex,
  root: DishNode,
  slot: IndexedSlot,
  create: boolean,
): DishNode | null {
  if (slot.group === -1) return root;
  const groupId = ids.byNode.group.get(ix.groupName[slot.group]);
  if (groupId === undefined) return null;
  const existing = root.members.find((m): m is DishNode => m.kind === "group" && m.id === groupId);
  if (existing) return existing;
  if (!create) return null;
  const fresh: DishNode = { kind: "group", id: groupId, members: [] };
  root.members.push(fresh);
  return fresh;
}

function membersOf(
  ix: GraphIndex,
  ids: IdIndex,
  root: DishNode,
  orderable: number,
  slotIndex: number,
): number[] {
  const slot = ix.slotsOfComposite[orderable]?.[slotIndex];
  if (!slot) return [];
  const container = containerFor(ids, ix, root, slot, false);
  if (!container) return [];
  const out: number[] = [];
  for (const member of container.members) {
    if (member.kind !== "ingredient") continue;
    const name = ids.byId.ingredient.get(member.id);
    const ing = name === undefined ? undefined : ix.ingByName.get(name);
    if (ing !== undefined && slot.options.includes(ing)) out.push(ing);
  }
  return out;
}

export function addToSlot(
  ix: GraphIndex,
  ids: IdIndex,
  root: DishNode,
  orderable: number,
  slotIndex: number,
  ing: number,
): void {
  const slot = ix.slotsOfComposite[orderable]?.[slotIndex];
  if (!slot) return;
  const container = containerFor(ids, ix, root, slot, true);
  if (!container) return;
  const dataId = ids.byNode.ingredient.get(ix.ingName[ing]);
  if (dataId === undefined) return;

  // At capacity the oldest member makes room, so a cap-of-1 slot reads as
  // "picking a new option replaces the current one".
  const capacity = slotCapacity(slot);
  let held = membersOf(ix, ids, root, orderable, slotIndex).length;
  while (held >= capacity) {
    const at = container.members.findIndex((m) => m.kind === "ingredient");
    if (at === -1) break;
    container.members.splice(at, 1);
    held--;
  }
  container.members.push({ kind: "ingredient", id: dataId });
}

export function removeFromSlot(
  ix: GraphIndex,
  ids: IdIndex,
  root: DishNode,
  orderable: number,
  slotIndex: number,
  occurrence: number,
): void {
  const slot = ix.slotsOfComposite[orderable]?.[slotIndex];
  if (!slot) return;
  const container = containerFor(ids, ix, root, slot, false);
  if (!container) return;
  let seen = 0;
  for (let i = 0; i < container.members.length; i++) {
    const member = container.members[i];
    if (member.kind !== "ingredient") continue;
    const name = ids.byId.ingredient.get(member.id);
    const ing = name === undefined ? undefined : ix.ingByName.get(name);
    if (ing === undefined || !slot.options.includes(ing)) continue;
    if (seen++ !== occurrence) continue;
    container.members.splice(i, 1);
    break;
  }
  // An emptied group bracket is removed rather than left as `{g0:}`, which the
  // grammar cannot round-trip.
  if (container !== root && container.members.length === 0) {
    const index = root.members.indexOf(container);
    if (index !== -1) root.members.splice(index, 1);
  }
}

/** Replaces one occurrence in a slot, in place, keeping chip order stable. */
function swapInSlot(
  ix: GraphIndex,
  ids: IdIndex,
  root: DishNode,
  orderable: number,
  slotIndex: number,
  occurrence: number,
  next: number,
): void {
  const slot = ix.slotsOfComposite[orderable]?.[slotIndex];
  if (!slot) return;
  const container = containerFor(ids, ix, root, slot, false);
  const dataId = ids.byNode.ingredient.get(ix.ingName[next]);
  if (!container || dataId === undefined) return;
  let seen = 0;
  for (const member of container.members) {
    if (member.kind !== "ingredient") continue;
    const name = ids.byId.ingredient.get(member.id);
    const ing = name === undefined ? undefined : ix.ingByName.get(name);
    if (ing === undefined || !slot.options.includes(ing)) continue;
    if (seen++ !== occurrence) continue;
    member.id = dataId;
    break;
  }
}

/** Fills the base, plus the topping when the composite requires one. */
function seedRequiredSlots(ix: GraphIndex, ids: IdIndex, dish: NodeDish, orderable: number): void {
  const slots = ix.slotsOfComposite[orderable] ?? [];
  const requiresTopping = Boolean(ix.doc.vertices.composite[orderable]?.toppingRequired);
  slots.forEach((slot, index) => {
    if (!slot.isBase && !requiresTopping) return;
    const option = slot.options[0];
    if (option !== undefined) addToSlot(ix, ids, dish.root, orderable, index, option);
  });
}

function newDish(ix: GraphIndex, ids: IdIndex, orderable = ix.orderables[0]): NodeDish | null {
  if (orderable === undefined) return null;
  const compositeId = ids.byNode.composite.get(ix.compositeName[orderable]);
  if (compositeId === undefined) return null;
  const dish: NodeDish = { root: { kind: "composite", id: compositeId, members: [] }, effects: [] };
  seedRequiredSlots(ix, ids, dish, orderable);
  return dish;
}

function retargetDish(ix: GraphIndex, ids: IdIndex, dish: NodeDish, orderable: number): void {
  const compositeId = ids.byNode.composite.get(ix.compositeName[orderable]);
  if (compositeId === undefined) return;
  dish.root = { kind: "composite", id: compositeId, members: [] };
  seedRequiredSlots(ix, ids, dish, orderable);
}

/** One chip's provenance: which slot it fills, and which copy within that slot. */
interface ChipRef {
  slotIndex: number;
  occurrence: number;
  ing: number;
}

/** Every chip a dish draws, flat and in slot-tree order — base first. */
function chipsOf(ix: GraphIndex, ids: IdIndex, dish: NodeDish, orderable: number): ChipRef[] {
  const out: ChipRef[] = [];
  const slots = ix.slotsOfComposite[orderable] ?? [];
  slots.forEach((_, slotIndex) => {
    membersOf(ix, ids, dish.root, orderable, slotIndex).forEach((ing, occurrence) => {
      out.push({ slotIndex, occurrence, ing });
    });
  });
  return out;
}

// ---------- rendering ----------

function renderBody(
  section: Section<NodeCustomerConfig[]>,
  deps: NodeCustomerSectionDeps,
  ids: IdIndex,
  draft: NodeCustomerConfig[],
  body: HTMLElement,
  chartUi: ChartUi,
): void {
  body.append(levelParamsBar(section, deps));

  const estimate = deps.currentEstimate?.() ?? null;
  if (estimate) {
    body.append(
      estimateBar(
        estimate,
        chartUi,
        () => {
          chartUi.open = !chartUi.open;
          section.render();
        },
        (key) => {
          chartUi[key] = !chartUi[key];
          section.render();
        },
      ),
    );
  }

  const row = el("div", { class: "customer-cards", "data-scroll-key": "customer-cards" });
  draft.forEach((customer, index) => {
    row.append(customerCard(section, deps, ids, draft, customer, index, estimate));
  });

  const addCard = el("div", { class: "customer-card add-card" }, ["＋"]);
  addCard.title = "Append a customer";
  addCard.addEventListener("click", () => {
    const dish = newDish(deps.ix, ids);
    draft.push({ typeId: 0, waitTime: 0, weatherEff: 0, dishes: dish ? [dish] : [] });
    section.commit("Add customer", 1);
  });
  row.append(addCard);

  Sortable.create(row, {
    animation: 150,
    draggable: ".customer-card:not(.add-card)",
    handle: ".customer-head",
    onEnd: (evt) => {
      if (evt.oldIndex === undefined || evt.newIndex === undefined) return;
      if (evt.oldIndex === evt.newIndex) return;
      const [moved] = draft.splice(evt.oldIndex, 1);
      draft.splice(Math.min(evt.newIndex, draft.length), 0, moved);
      section.commit("Reorder customers");
    },
  });

  body.append(row);

  // Live validation against the graph — a dish naming a retired id, or leaving
  // a required topping empty, says so here rather than at play time.
  const problems: string[] = [];
  draft.forEach((customer, ci) => {
    customer.dishes.forEach((dish, di) => {
      for (const issue of resolveOrder(deps.ix, dish, ids).issues) {
        problems.push(`Customer ${ci + 1}, dish ${di + 1}: ${describeIssue(issue)}`);
      }
    });
  });
  if (problems.length > 0) {
    body.append(
      el("div", { class: "warnings" }, [
        el("strong", {}, [`${problems.length} dish issue(s)`]),
        ...problems.slice(0, 12).map((p) => el("div", {}, [p])),
      ]),
    );
  }
}

function estimateBar(
  estimate: EstimateResult,
  chartUi: ChartUi,
  onToggleChart: () => void,
  onToggleVisibility: (key: keyof ChartVisibility) => void,
): HTMLElement {
  const peakWaste = estimate.perCustomer.reduce((n, c) => Math.max(n, c.gridWaste), 0);
  const detours = estimate.perCustomer.reduce((n, c) => n + c.detours, 0);
  const summary = estimate.solvable
    ? `Solvable — ${estimate.totalPicks} picks for ${estimate.servedCount} customers`
    : `Unsolvable — served ${estimate.servedCount} of ${estimate.totalCustomers} after ${estimate.totalPicks} picks`;

  const parts: (string | HTMLElement)[] = [
    button(chartUi.open ? "▾" : "▸", onToggleChart, {
      class: "icon-btn",
      title: "Show grid occupancy across the whole run, pick by pick",
    }),
    el("strong", {}, [estimate.solvable ? "✓ " : "⚠ ", summary]),
  ];
  if (estimate.reason) parts.push(el("span", { class: "estimate-reason" }, [estimate.reason]));
  parts.push(
    el("span", { class: "estimate-metric" }, [`peak waste ${peakWaste}`]),
    el("span", { class: "estimate-metric" }, [`${detours} detour${detours === 1 ? "" : "s"}`]),
  );

  const bar = el("div", { class: `estimate-bar${estimate.solvable ? "" : " unsolvable"}` }, parts);
  if (!chartUi.open) return bar;
  return el("div", { class: "estimate-panel" }, [
    bar,
    occupancyChartEl(estimate.occupancyHistory, estimate.gridCapacity, chartUi, onToggleVisibility),
  ]);
}

function levelParamsBar(
  section: Section<NodeCustomerConfig[]>,
  deps: NodeCustomerSectionDeps,
): HTMLElement {
  const refresh = () => {
    deps.onSaved();
    section.render();
  };

  const weightsField = readOnlyField("Ingredient Weights", deps.level.ingredientWeights ?? "", () => {
    const initial = deps.level.ingredientWeights
      ? parseIngredientWeights(deps.level.ingredientWeights)
      : new Map(deps.projected.map.cookedIngredients.map((c) => [c.id, DEFAULT_INGREDIENT_WEIGHT]));
    openIngredientWeightsDialog(deps.projected.map, initial, (weights) => {
      deps.level.ingredientWeights = serializeIngredientWeights(weights);
      refresh();
    });
  });

  const dishSeqField = readOnlyField(
    "Customer Dishes Sequence",
    deps.level.customerDishesSequence ?? "",
    () => {
      const initial = deps.level.customerDishesSequence
        ? parseDishCountSequence(deps.level.customerDishesSequence)
        : [1, 1, 1];
      openDishCountDialog(initial, (counts) => {
        deps.level.customerDishesSequence = serializeDishCountSequence(counts);
        refresh();
      });
    },
  );

  const curveField = readOnlyField("Complexity Curve", deps.level.complexityCurve ?? "", () => {
    const initial = deps.level.complexityCurve
      ? parseCurve(deps.level.complexityCurve, defaultCurve(1, DEFAULT_MAX_DISH_SLOTS))
      : defaultCurve(1, DEFAULT_MAX_DISH_SLOTS);
    openCurveDialog("Complexity Curve", initial, (curve) => {
      deps.level.complexityCurve = serializeCurve(curve);
      refresh();
    });
  });

  return el("div", { class: "level-params-bar" }, [weightsField, dishSeqField, curveField]);
}

function readOnlyField(label: string, value: string, onEdit: () => void): HTMLElement {
  const input = el("input", { type: "text", value, readonly: "true" }) as HTMLInputElement;
  return el("label", { class: "field level-param-field" }, [
    label,
    el("div", { class: "level-param-row" }, [input, button("Edit", onEdit, { class: "small-btn" })]),
  ]);
}

function openDishCountDialog(initial: number[], onApply: (counts: number[]) => void): void {
  const close = () => overlay.remove();
  let counts = [...initial];
  const panel = el("div", { class: "auto-generate-panel" }, [
    dishCountEditor(initial, (next) => (counts = next)),
    el("div", { class: "auto-generate-actions" }, [
      button("Cancel", close),
      button("Apply", () => {
        onApply(counts);
        close();
      }, { class: "primary" }),
    ]),
  ]);
  const overlay = el("div", { class: "overlay-panel" }, [
    el("div", { class: "definitions-head" }, [
      el("h2", {}, ["Customer Dishes Sequence"]),
      button("✕ Close", close, { class: "primary" }),
    ]),
    panel,
  ]);
  overlay.addEventListener("click", (e) => {
    if (e.target === overlay) close();
  });
  document.body.append(overlay);
}

function customerCard(
  section: Section<NodeCustomerConfig[]>,
  deps: NodeCustomerSectionDeps,
  ids: IdIndex,
  draft: NodeCustomerConfig[],
  customer: NodeCustomerConfig,
  index: number,
  estimate: EstimateResult | null,
): HTMLElement {
  const { ix } = deps;
  const staff = isStaff(customer);
  const timed = customer.weatherEff !== 0 || customer.waitTime > 0;
  const card = el("div", { class: `customer-card${staff ? " staff" : ""}${timed ? " timed" : ""}` });

  const cost = estimate?.perCustomer.find((c) => c.index === index);
  if (cost) card.style.setProperty("--customer-color", customerColor(index));
  if (cost && estimate) {
    const worst = estimate.perCustomer.reduce((n, c) => Math.max(n, c.gridOccupied), 0);
    const bar = el("div", {
      class: "difficulty-bar",
      title: `Peak grid pressure: ${cost.gridOccupied} cell(s) — the worst customer in this level peaks at ${worst}`,
    });
    bar.style.background = difficultyColor(difficultyRatio(cost.gridOccupied, estimate.perCustomer));
    card.append(bar);
  }

  const waitInput = el("input", {
    type: "number",
    value: String(customer.waitTime),
    title: "Patience timer in seconds (0 = no limit)",
  }) as HTMLInputElement;
  waitInput.addEventListener("change", () => {
    customer.waitTime = Number(waitInput.value) || 0;
    section.commit("Set wait time");
  });

  const weatherToggle = button(
    customer.weatherEff ? "🌧" : "☁",
    () => {
      customer.weatherEff = customer.weatherEff ? 0 : 1;
      section.commit("Toggle weather effect");
    },
    {
      class: `weather-toggle${customer.weatherEff ? " on" : ""}`,
      title: "Weather-affected: bad weather halves this customer's patience",
    },
  );

  const def = typeDef(deps.defs, customer.typeId);
  const typeMark = def && def.id !== 0 ? ` ${def.icon || def.name}` : "";
  const head = el("div", { class: "customer-head" }, [
    el("span", { class: "cust-index" }, [`#${index + 1}${typeMark}`]),
    el("span", { class: "wait-badge" }, [customer.waitTime === 0 ? "∞" : "", waitInput]),
    weatherToggle,
  ]);
  if (cost) {
    head.append(
      el("span", { class: "cust-cost" }, [
        el("span", { class: "cost-occupied" }, [`▦${cost.gridOccupied}`]),
        el("span", { class: `cost-waste${cost.gridWaste > 0 ? " bad" : ""}` }, [`✖${cost.gridWaste}`]),
      ]),
    );
  }
  head.addEventListener("contextmenu", (e) =>
    showContextMenu(e, cardMenu(section, deps, ids, draft, customer, index), {
      title: `Customer #${index + 1}`,
    }),
  );
  card.append(head);

  if (staff) {
    const amountInput = el("input", {
      type: "number",
      min: "1",
      value: String(customer.staffAmount ?? 1),
      title: "How many dirty stacks this staff clears on arrival",
    }) as HTMLInputElement;
    amountInput.addEventListener("change", () => {
      customer.staffAmount = Math.max(1, Number(amountInput.value) || 1);
      section.commit("Set staff stack amount");
    });
    card.append(el("div", { class: "staff-note" }, ["Staff — clears ", amountInput, " dirty stack(s)"]));
    return card;
  }

  customer.dishes.forEach((dish, di) => {
    const orderable = orderableOf(ix, ids, dish);
    const dishRow = el("div", { class: "dish-row" }, [
      el("span", { class: "dish-label" }, [`D${di + 1}`]),
    ]);
    const chipsRow = el("div", { class: "dish-chips" });

    if (orderable === -1) {
      chipsRow.append(el("span", { class: "warnings" }, [`unknown composite ${dish.root.id}`]));
    } else {
      const slots = ix.slotsOfComposite[orderable] ?? [];
      for (const ref of chipsOf(ix, ids, dish, orderable)) {
        const dataId = ids.byNode.ingredient.get(ix.ingName[ref.ing]);
        const chip = el("span", { class: "chip icon-chip dish-chip" }, [
          dataId === undefined ? el("span", { class: "icon" }, ["❔"]) : cookedIconEl(dataId, 64),
        ]);
        const slot = slots[ref.slotIndex];
        chip.title =
          `${ix.doc.vertices.ingredient[ref.ing]?.displayName ?? ix.ingName[ref.ing]} — ` +
          (slot?.isBase ? "base" : slot?.group === -1 ? "item" : ix.groupName[slot?.group ?? 0]);

        // The legacy swap picker, narrowed to this chip's own slot: swapping to
        // an ingredient from a different slot would be a different dish shape,
        // not a swap.
        chip.addEventListener("contextmenu", (e) => {
          e.preventDefault();
          e.stopPropagation();
          if (!slot) return;
          const counts = new Map<number, number>();
          for (const other of chipsOf(ix, ids, dish, orderable)) {
            if (other.slotIndex !== ref.slotIndex) continue;
            counts.set(other.ing, (counts.get(other.ing) ?? 0) + 1);
          }
          counts.set(ref.ing, Math.max(0, (counts.get(ref.ing) ?? 1) - 1));

          const wrap = el("div", { class: "ctx-swap" });
          wrap.append(
            addPickerGrid(
              slot.options.map((option, at) => ({
                id: option,
                label: ix.doc.vertices.ingredient[option]?.displayName ?? ix.ingName[option],
                icon: iconFor(ix, ids, option),
                limit: (slot.optionMax[at] ?? -1) > 0 ? slot.optionMax[at] : undefined,
              })),
              counts,
              (option) => {
                swapInSlot(ix, ids, dish.root, orderable, ref.slotIndex, ref.occurrence, option);
                section.commit("Swap dish ingredient");
                closeContextMenu();
              },
            ),
            button(
              "Remove",
              () => {
                removeFromSlot(ix, ids, dish.root, orderable, ref.slotIndex, ref.occurrence);
                section.commit("Remove ingredient from dish", 0, 1);
                closeContextMenu();
              },
              { class: "danger ctx-swap-remove" },
            ),
          );
          showContextContent(e, wrap, { title: `Swap: ${chip.title}` });
        });
        chipsRow.append(chip);
      }

      // `＋` adds, exactly as legacy — but grouped by slot, because "which slot
      // does this ingredient fill" is the one thing a flat picker cannot say.
      const addChip = button(
        "＋",
        (e) => {
          showContextContent(e, slotPicker(section, deps, ids, dish, orderable), {
            title: `Dish ${di + 1}`,
          });
        },
        { class: "chip add-chip" },
      );
      chipsRow.append(addChip);
    }

    dishRow.append(chipsRow);

    // THE difference from legacy: a node dish is a bracket tree, so its dish
    // menu is where that tree is configured — the composite it is an order of,
    // and each nested group's contents.
    dishRow.addEventListener("contextmenu", (e) =>
      showContextMenu(e, dishMenu(section, deps, ids, customer, dish, di, orderable), {
        title: `Dish ${di + 1}`,
      }),
    );
    card.append(dishRow);
  });

  card.append(
    button(
      "+ Dish",
      () => {
        const dish = newDish(ix, ids);
        if (!dish) return;
        customer.dishes.push(dish);
        section.commit("Add dish", 1);
      },
      { class: "small-btn add-dish" },
    ),
  );

  return card;
}

function iconFor(ix: GraphIndex, ids: IdIndex, ing: number): HTMLElement {
  const dataId = ids.byNode.ingredient.get(ix.ingName[ing]);
  return dataId === undefined ? el("span", { class: "icon" }, ["❔"]) : cookedIconEl(dataId, 64);
}

/** The `＋` picker: one option grid per slot, so every add lands somewhere legal. */
function slotPicker(
  section: Section<NodeCustomerConfig[]>,
  deps: NodeCustomerSectionDeps,
  ids: IdIndex,
  dish: NodeDish,
  orderable: number,
): HTMLElement {
  const { ix } = deps;
  const wrap = el("div", { class: "ctx-swap" });
  const slots = ix.slotsOfComposite[orderable] ?? [];

  slots.forEach((slot, slotIndex) => {
    const held = membersOf(ix, ids, dish.root, orderable, slotIndex);
    const capacity = slotCapacity(slot);
    const label = slot.isBase
      ? "Base"
      : slot.group === -1
        ? "Item"
        : (ix.doc.vertices.group[slot.group]?.displayName ?? ix.groupName[slot.group]);

    const counts = new Map<number, number>();
    for (const ing of held) counts.set(ing, (counts.get(ing) ?? 0) + 1);

    wrap.append(
      el("div", { class: "slot-picker-head" }, [
        `${label} — ${held.length}/${capacity === Number.POSITIVE_INFINITY ? "∞" : capacity}`,
      ]),
      addPickerGrid(
        slot.options.map((option, at) => ({
          id: option,
          label: ix.doc.vertices.ingredient[option]?.displayName ?? ix.ingName[option],
          icon: iconFor(ix, ids, option),
          limit: (slot.optionMax[at] ?? -1) > 0 ? slot.optionMax[at] : undefined,
        })),
        counts,
        (option) => {
          addToSlot(ix, ids, dish.root, orderable, slotIndex, option);
          section.commit("Add ingredient to dish", 1, 0);
        },
      ),
    );
  });
  return wrap;
}

/**
 * The dish menu — the one place the bracket tree is edited directly.
 *
 * "Order type" repoints the whole dish at another composite (re-seeding its
 * required slots); each slot below expands into its own option grid, so a
 * nested group is edited as a group rather than as a run of loose chips.
 */
function dishMenu(
  section: Section<NodeCustomerConfig[]>,
  deps: NodeCustomerSectionDeps,
  ids: IdIndex,
  customer: NodeCustomerConfig,
  dish: NodeDish,
  dishIndex: number,
  orderable: number,
): MenuItem[] {
  const { ix } = deps;
  const items: MenuItem[] = [
    {
      label: "Order type…",
      expand: () =>
        el(
          "div",
          { class: "ctx-swap" },
          ix.orderables.map((composite) =>
            button(
              `${composite === orderable ? "● " : "○ "}${
                ix.doc.vertices.composite[composite]?.displayName ?? ix.compositeName[composite]
              }`,
              () => {
                retargetDish(ix, ids, dish, composite);
                section.commit("Change dish order type");
                closeContextMenu();
              },
              { class: "ctx-orderable" },
            ),
          ),
        ),
    },
  ];

  if (orderable !== -1) {
    const slots = ix.slotsOfComposite[orderable] ?? [];
    slots.forEach((slot, slotIndex) => {
      const held = membersOf(ix, ids, dish.root, orderable, slotIndex);
      const capacity = slotCapacity(slot);
      const label = slot.isBase
        ? "Base"
        : slot.group === -1
          ? "Item"
          : (ix.doc.vertices.group[slot.group]?.displayName ?? ix.groupName[slot.group]);
      items.push({
        label: `${label} (${held.length}/${capacity === Number.POSITIVE_INFINITY ? "∞" : capacity})`,
        expand: () => slotEditor(section, deps, ids, dish, orderable, slotIndex),
      });
    });
  }

  items.push(
    {
      label: "Duplicate dish",
      separator: true,
      onSelect: () => {
        customer.dishes.splice(dishIndex + 1, 0, structuredClone(dish));
        section.commit("Duplicate dish", 1, 0);
      },
    },
    {
      label: "Remove dish",
      danger: true,
      onSelect: () => {
        customer.dishes.splice(dishIndex, 1);
        section.commit("Remove dish", 0, 1);
      },
    },
  );
  return items;
}

/** One slot's option grid, re-rendered in place so counts stay live while clicking. */
function slotEditor(
  section: Section<NodeCustomerConfig[]>,
  deps: NodeCustomerSectionDeps,
  ids: IdIndex,
  dish: NodeDish,
  orderable: number,
  slotIndex: number,
): HTMLElement {
  const { ix } = deps;
  const slot = ix.slotsOfComposite[orderable]?.[slotIndex];
  const wrap = el("div", { class: "ctx-swap" });
  if (!slot) return wrap;

  const caption = el("div", { class: "slot-picker-head" });
  const grid = el("div", { class: "slot-editor-grid" });

  const rerender = () => {
    const held = membersOf(ix, ids, dish.root, orderable, slotIndex);
    const capacity = slotCapacity(slot);
    caption.textContent =
      `${held.length}/${capacity === Number.POSITIVE_INFINITY ? "∞" : capacity} filled` +
      (slot.isBase ? " · base (required)" : "");

    const counts = new Map<number, number>();
    for (const ing of held) counts.set(ing, (counts.get(ing) ?? 0) + 1);

    grid.replaceChildren(
      addPickerGrid(
        slot.options.map((option, at) => ({
          id: option,
          label: ix.doc.vertices.ingredient[option]?.displayName ?? ix.ingName[option],
          icon: iconFor(ix, ids, option),
          limit: (slot.optionMax[at] ?? -1) > 0 ? slot.optionMax[at] : undefined,
        })),
        counts,
        (option) => {
          addToSlot(ix, ids, dish.root, orderable, slotIndex, option);
          section.commit(`Add ${ix.ingName[option]}`);
          rerender();
        },
      ),
      ...held.map((ing, occurrence) =>
        button(
          `✕ ${ix.doc.vertices.ingredient[ing]?.displayName ?? ix.ingName[ing]}`,
          () => {
            removeFromSlot(ix, ids, dish.root, orderable, slotIndex, occurrence);
            section.commit(`Remove ${ix.ingName[ing]}`);
            rerender();
          },
          { class: "small-btn ctx-slot-remove" },
        ),
      ),
    );
  };

  wrap.append(caption, grid);
  rerender();
  return wrap;
}

function cardMenu(
  section: Section<NodeCustomerConfig[]>,
  deps: NodeCustomerSectionDeps,
  ids: IdIndex,
  draft: NodeCustomerConfig[],
  customer: NodeCustomerConfig,
  index: number,
): MenuItem[] {
  return [
    ...deps.defs.customerTypes.map((type) => ({
      label: `${type.icon || ""} ${type.name}`.trim(),
      active: customer.typeId === type.id,
      onSelect: () => {
        customer.typeId = type.id;
        if (type.id === CUSTOMER_STAFF) customer.dishes = [];
        else if (customer.dishes.length === 0) {
          const dish = newDish(deps.ix, ids);
          if (dish) customer.dishes.push(dish);
        }
        section.commit("Change customer type");
      },
    })),
    {
      label: "Duplicate",
      separator: true,
      onSelect: () => {
        draft.splice(index + 1, 0, structuredClone(customer));
        section.commit("Duplicate customer", 1, 0);
      },
    },
    {
      label: "Remove",
      danger: true,
      onSelect: () => {
        draft.splice(index, 1);
        section.commit("Remove customer", 0, 1);
      },
    },
  ];
}
