// The Auto Generate dialog, on the node graph.
//
// The dialog CHROME is the legacy one, deliberately: the dish-count editor, the
// ingredient weight grid and the curve editor are imported unchanged, so a
// designer who knows the legacy dialog already knows this one.
//
// What changed is what the Generate button runs. It used to build customers
// only, then chain into the queue section's own Auto Generate — two steps that
// could each succeed while the level they added up to was unwinnable. It now
// runs the shared pipeline (levelpath/generateLevel.ts), which builds
// customers AND their queue from one seed and verifies the result with the
// difficulty estimator, walking the shuffle ceiling down and then trying other
// seeds until the level can actually be won. That is the same pipeline the
// Level Path tab's Generate buttons run, so a level generated in either place
// is generated the same way.
//
// The weight grid is keyed by DATA ID (it reads the projected `MapDef`); the
// generator works in dense ingredient indices. The pipeline owns that
// translation now, so this file no longer does it.

import { button, el } from "../dom.ts";
import {
  DEFAULT_DISH_COUNT_SEQUENCE,
  DEFAULT_MAX_DISH_SLOTS,
  parseDishCountSequence,
  serializeDishCountSequence,
} from "../design/autoGenerate.ts";
import { dishCountEditor } from "../design/autoGenerateDialog.ts";
import { createCurveWithPresets, defaultCurve, parseCurve, serializeCurve } from "../design/curveEditor.ts";
import type { CurveState } from "../design/curveEditor.ts";
import type { EstimateScenario } from "../design/estimateScenario.ts";
import {
  createIngredientWeightGrid,
  DEFAULT_INGREDIENT_WEIGHT,
  parseIngredientWeights,
  serializeIngredientWeights,
} from "../design/ingredientWeightEditor.ts";
import { generateLevel } from "../levelpath/generateLevel.ts";
import type { GenerateLevelResult } from "../levelpath/generateLevel.ts";
import { loadConfig } from "../levelpath/config.ts";
import type { GraphIndex } from "../../core/nodeIndex.ts";
import type { NodeCustomerConfig } from "../../core/nodeParser.ts";
import type { IdIndex } from "../../data/nodeIdTable.ts";
import type { LevelData } from "../../data/mapLoader.ts";
import type { ProjectedMap } from "../../data/nodeGraphToMapDef.ts";

export interface NodeGenerateDeps {
  ix: GraphIndex;
  ids: IdIndex;
  projected: ProjectedMap;
  level: LevelData;
  currentCustomers(): NodeCustomerConfig[];
  /** Scoring scenario the verification estimate runs under. */
  scenario?: EstimateScenario;
  /**
   * The pipeline has already written its result into `deps.level`. The caller
   * re-reads the level's strings — it must not try to merge, because a
   * generated level replaces the customers AND the queue together.
   */
  onGenerated(result: GenerateLevelResult): void;
}

/** Survives one dialog close so re-opening does not lose a curve the designer just shaped. */
let cachedCurve: CurveState | null = null;

export function openNodeGenerateDialog(deps: NodeGenerateDeps): void {
  const close = () => overlay.remove();

  const existing = deps.currentCustomers();
  const storedCounts = deps.level.customerDishesSequence
    ? parseDishCountSequence(deps.level.customerDishesSequence)
    : [];
  const initialCounts = existing.length
    ? existing.map((c) => (c.typeId === 1 ? -1 : c.dishes.length))
    : storedCounts.length
      ? storedCounts
      : [...DEFAULT_DISH_COUNT_SEQUENCE];

  const storedWeights = deps.level.ingredientWeights
    ? parseIngredientWeights(deps.level.ingredientWeights)
    : null;
  let weightsByDataId =
    storedWeights && storedWeights.size > 0
      ? storedWeights
      : new Map(deps.projected.map.cookedIngredients.map((c) => [c.id, DEFAULT_INGREDIENT_WEIGHT]));

  let dishCounts = [...initialCounts];
  let curveState = deps.level.complexityCurve
    ? parseCurve(deps.level.complexityCurve, cachedCurve ?? defaultCurve(1, DEFAULT_MAX_DISH_SLOTS))
    : cachedCurve
      ? structuredClone(cachedCurve)
      : defaultCurve(1, DEFAULT_MAX_DISH_SLOTS);

  const weightGrid = createIngredientWeightGrid(deps.projected.map, weightsByDataId, (next) => {
    weightsByDataId = next;
  });

  const seedInput = el("input", {
    type: "number",
    min: "0",
    step: "1",
    placeholder: "auto",
    value: deps.level.randomSeed === undefined ? "" : String(deps.level.randomSeed),
  }) as HTMLInputElement;
  seedInput.title =
    "Every random draw comes from this seed, so the same seed rebuilds the same level. " +
    "Leave it blank to let the generator pick one — it will try several until the level is winnable, " +
    "then write the winning one back here.";

  const panel = el("div", { class: "auto-generate-panel" }, [
    el("h3", {}, ["Customers (dish count per customer — -1 = Staff, 0 = Auto)"]),
    dishCountEditor(initialCounts, (next) => (dishCounts = next)),
    el("h3", {}, ["Ingredient Weights"]),
    el("div", { class: "ingredient-toggle-actions" }, [
      button("Enable All", () => weightGrid.setAll(DEFAULT_INGREDIENT_WEIGHT), { class: "small-btn" }),
      button("Disable All", () => weightGrid.setAll(0), { class: "small-btn" }),
    ]),
    weightGrid.element,
    el("h3", {}, ["Complexity Curve (total ingredients per customer, by normalized order position)"]),
    createCurveWithPresets(curveState, (next) => {
      curveState = next;
      cachedCurve = next;
    }),
    el("h3", {}, ["Random Seed"]),
    el("label", { class: "field" }, ["Seed (blank = pick one)", seedInput]),
    el("p", { class: "muted" }, [
      "Each dish picks an orderable first, then fills its slots — so every generated dish is " +
        "well-formed by construction, respects each slot's cap, and fills a required topping. " +
        "The ingredient queue is generated from the resulting orders and verified with the difficulty " +
        "estimator; if the level cannot be won, the shuffle distance is lowered a step at a time and, " +
        "failing that, another seed is tried.",
    ]),
    el("div", { class: "auto-generate-actions" }, [
      button("Cancel", close),
      button(
        "Generate",
        (event) => {
          if (
            deps.currentCustomers().length > 0 &&
            !confirm("Auto-generate replaces every customer AND the whole queue in this level. Continue?")
          ) {
            return;
          }
          // The pipeline reads its inputs off the level, so the dialog's job is
          // to record what the designer chose and then hand over.
          deps.level.ingredientWeights = serializeIngredientWeights(weightsByDataId);
          deps.level.customerDishesSequence = serializeDishCountSequence(dishCounts);
          deps.level.complexityCurve = serializeCurve(curveState);
          const seed = seedInput.value.trim();
          if (seed === "") delete deps.level.randomSeed;
          else deps.level.randomSeed = Math.max(0, Math.trunc(Number(seed) || 0)) >>> 0;

          // A full pipeline run is seconds of straight-line work, so paint a
          // busy label before starting it: a click that looks like it did
          // nothing is worse than a wait. The timer (not rAF) is deliberate —
          // rAF never fires in a hidden tab.
          const btn = event.currentTarget as HTMLButtonElement;
          btn.textContent = "Generating…";
          btn.disabled = true;
          setTimeout(() => {
            const result = generateLevel(
              deps.level,
              {
                ix: deps.ix,
                ids: deps.ids,
                projected: deps.projected,
                ...(deps.scenario ? { scenario: deps.scenario } : {}),
              },
              // How big a generated level may be is a project-wide setting,
              // edited in Level Path's config bar. Reading it here rather than
              // duplicating the control keeps one answer to the question.
              { bounds: loadConfig().bounds },
            );
            deps.onGenerated(result);
            close();
            const notes = [...result.errors, ...result.warnings];
            if (notes.length > 0) {
              alert(`${result.ok ? "Generated with warnings" : "Generate failed"}:\n\n${notes.join("\n")}`);
            }
          }, 0);
        },
        { class: "primary" },
      ),
    ]),
  ]);

  const overlay = el("div", { class: "overlay-panel" }, [
    el("div", { class: "definitions-head" }, [
      el("h2", {}, ["Auto Generate Level"]),
      button("✕ Close", close, { class: "primary" }),
    ]),
    panel,
  ]);
  overlay.addEventListener("click", (e) => {
    if (e.target === overlay) close();
  });
  document.body.append(overlay);
}
