// The Auto Generate Customers dialog, on the node graph.
//
// The dialog CHROME is the legacy one, deliberately: the dish-count editor, the
// ingredient weight grid and the curve editor are imported unchanged, so a
// designer who knows the legacy dialog already knows this one. Only the
// generator behind the Generate button differs, because a bracket dish has to
// be built from an orderable outward — see nodeGenerate.ts.
//
// The weight grid is keyed by DATA ID (it reads the projected `MapDef`), while
// the generator works in dense ingredient indices. The translation happens here
// and nowhere else.

import { button, el } from "../dom.ts";
import {
  DEFAULT_DISH_COUNT_SEQUENCE,
  DEFAULT_MAX_DISH_SLOTS,
  parseDishCountSequence,
  serializeDishCountSequence,
} from "../design/autoGenerate.ts";
import { dishCountEditor } from "../design/autoGenerateDialog.ts";
import { createCurveWithPresets, defaultCurve, parseCurve, serializeCurve } from "../design/curveEditor.ts";
import type { CurveState } from "../design/curveEditor.ts";
import {
  createIngredientWeightGrid,
  DEFAULT_INGREDIENT_WEIGHT,
  parseIngredientWeights,
  serializeIngredientWeights,
} from "../design/ingredientWeightEditor.ts";
import { generateNodeCustomers } from "./nodeGenerate.ts";
import type { GraphIndex } from "../../core/nodeIndex.ts";
import type { NodeCustomerConfig } from "../../core/nodeParser.ts";
import type { IdIndex } from "../../data/nodeIdTable.ts";
import type { LevelData } from "../../data/mapLoader.ts";
import type { ProjectedMap } from "../../data/nodeGraphToMapDef.ts";

export interface NodeGenerateDeps {
  ix: GraphIndex;
  ids: IdIndex;
  projected: ProjectedMap;
  level: LevelData;
  currentCustomers(): NodeCustomerConfig[];
  onGenerate(customers: NodeCustomerConfig[]): void;
}

/** Survives one dialog close so re-opening does not lose a curve the designer just shaped. */
let cachedCurve: CurveState | null = null;

export function openNodeGenerateDialog(deps: NodeGenerateDeps): void {
  const close = () => overlay.remove();

  const existing = deps.currentCustomers();
  const storedCounts = deps.level.customerDishesSequence
    ? parseDishCountSequence(deps.level.customerDishesSequence)
    : [];
  const initialCounts = existing.length
    ? existing.map((c) => (c.typeId === 1 ? -1 : c.dishes.length))
    : storedCounts.length
      ? storedCounts
      : [...DEFAULT_DISH_COUNT_SEQUENCE];

  const storedWeights = deps.level.ingredientWeights
    ? parseIngredientWeights(deps.level.ingredientWeights)
    : null;
  let weightsByDataId =
    storedWeights && storedWeights.size > 0
      ? storedWeights
      : new Map(deps.projected.map.cookedIngredients.map((c) => [c.id, DEFAULT_INGREDIENT_WEIGHT]));

  let dishCounts = [...initialCounts];
  let curveState = deps.level.complexityCurve
    ? parseCurve(deps.level.complexityCurve, cachedCurve ?? defaultCurve(1, DEFAULT_MAX_DISH_SLOTS))
    : cachedCurve
      ? structuredClone(cachedCurve)
      : defaultCurve(1, DEFAULT_MAX_DISH_SLOTS);

  const weightGrid = createIngredientWeightGrid(deps.projected.map, weightsByDataId, (next) => {
    weightsByDataId = next;
  });

  const panel = el("div", { class: "auto-generate-panel" }, [
    el("h3", {}, ["Customers (dish count per customer — -1 = Staff, 0 = Auto)"]),
    dishCountEditor(initialCounts, (next) => (dishCounts = next)),
    el("h3", {}, ["Ingredient Weights"]),
    el("div", { class: "ingredient-toggle-actions" }, [
      button("Enable All", () => weightGrid.setAll(DEFAULT_INGREDIENT_WEIGHT), { class: "small-btn" }),
      button("Disable All", () => weightGrid.setAll(0), { class: "small-btn" }),
    ]),
    weightGrid.element,
    el("h3", {}, ["Complexity Curve (total ingredients per customer, by normalized order position)"]),
    createCurveWithPresets(curveState, (next) => {
      curveState = next;
      cachedCurve = next;
    }),
    el("p", { class: "muted" }, [
      "Each dish picks an orderable first, then fills its slots — so every generated dish is " +
        "well-formed by construction, respects each slot's cap, and fills a required topping.",
    ]),
    el("div", { class: "auto-generate-actions" }, [
      button("Cancel", close),
      button(
        "Generate",
        () => {
          if (
            deps.currentCustomers().length > 0 &&
            !confirm("Auto-generate replaces every customer in this level. Continue?")
          ) {
            return;
          }
          deps.level.ingredientWeights = serializeIngredientWeights(weightsByDataId);
          deps.level.customerDishesSequence = serializeDishCountSequence(dishCounts);
          deps.level.complexityCurve = serializeCurve(curveState);

          // data id -> dense ingredient index, the generator's own space.
          const weights = new Map<number, number>();
          for (const [dataId, weight] of weightsByDataId) {
            const dense = deps.projected.denseOf.get(dataId);
            if (dense !== undefined && weight > 0) weights.set(dense, weight);
          }
          const warnings: string[] = [];
          const generated = generateNodeCustomers(deps.ix, deps.ids, {
            dishCounts,
            weights,
            curve: curveState,
            onWarning: (message) => warnings.push(message),
          });
          deps.onGenerate(generated);
          if (warnings.length > 0) {
            alert(`Customer generation warning:\n\n${warnings.join("\n")}`);
          }
          close();
        },
        { class: "primary" },
      ),
    ]),
  ]);

  const overlay = el("div", { class: "overlay-panel" }, [
    el("div", { class: "definitions-head" }, [
      el("h2", {}, ["Auto Generate Customers"]),
      button("✕ Close", close, { class: "primary" }),
    ]),
    panel,
  ]);
  overlay.addEventListener("click", (e) => {
    if (e.target === overlay) close();
  });
  document.body.append(overlay);
}
