// The Auto Generate dialog, on the node graph.
//
// The dialog CHROME is the legacy one, deliberately: the dish-count editor, the
// ingredient weight grid and the curve editor are imported unchanged, so a
// designer who knows the legacy dialog already knows this one.
//
// What changed is what the Generate button runs. It used to build customers
// only, then chain into the queue section's own Auto Generate — two steps that
// could each succeed while the level they added up to was unwinnable. It now
// runs the shared pipeline (levelpath/generateLevel.ts), which builds
// customers AND their queue from one seed and verifies the result with the
// difficulty estimator, walking the shuffle ceiling down and then trying other
// seeds until the level can actually be won. That is the same pipeline the
// Level Path tab's Generate buttons run, so a level generated in either place
// is generated the same way.
//
// The weight grid is keyed by DATA ID (it reads the projected `MapDef`); the
// generator works in dense ingredient indices. The pipeline owns that
// translation now, so this file no longer does it.

import { button, el } from "../dom.ts";
import {
  DEFAULT_DISH_COUNT_SEQUENCE,
  DEFAULT_MAX_DISH_SLOTS,
  parseDishCountSequence,
  serializeDishCountSequence,
} from "../design/autoGenerate.ts";
import { dishCountEditor } from "../design/autoGenerateDialog.ts";
import { createCurveWithPresets, defaultCurve, parseCurve, serializeCurve } from "../design/curveEditor.ts";
import type { CurveState } from "../design/curveEditor.ts";
import type { EstimateScenario } from "../design/estimateScenario.ts";
import {
  DEFAULT_INGREDIENT_WEIGHT,
  parseWeightSet,
  serializeWeightSet,
} from "../design/ingredientWeightEditor.ts";
import type { WeightSet } from "../design/ingredientWeightEditor.ts";
import { createDishWeightEditor } from "../levelpath/dishWeightEditor.ts";
import { generateLevel } from "../levelpath/generateLevel.ts";
import type { GenerateLevelResult } from "../levelpath/generateLevel.ts";
import { loadConfig } from "../levelpath/config.ts";
import { createObstacleEditor } from "../levelpath/obstacleEditor.ts";
import { parseObstacles, serializeObstacles } from "../levelpath/obstacles.ts";
import type { GraphIndex } from "../../core/nodeIndex.ts";
import type { NodeCustomerConfig } from "../../core/nodeParser.ts";
import type { IdIndex } from "../../data/nodeIdTable.ts";
import type { LevelData } from "../../data/mapLoader.ts";
import type { ProjectedMap } from "../../data/nodeGraphToMapDef.ts";

export interface NodeGenerateDeps {
  ix: GraphIndex;
  ids: IdIndex;
  projected: ProjectedMap;
  level: LevelData;
  currentCustomers(): NodeCustomerConfig[];
  /** Scoring scenario the verification estimate runs under. */
  scenario?: EstimateScenario;
  /**
   * The pipeline has already written its result into `deps.level`. The caller
   * re-reads the level's strings — it must not try to merge, because a
   * generated level replaces the customers AND the queue together.
   */
  onGenerated(result: GenerateLevelResult): void;
}

/** Survives one dialog close so re-opening does not lose a curve the designer just shaped. */
let cachedCurve: CurveState | null = null;

export function openNodeGenerateDialog(deps: NodeGenerateDeps): void {
  const close = () => overlay.remove();

  const existing = deps.currentCustomers();
  const storedCounts = deps.level.customerDishesSequence
    ? parseDishCountSequence(deps.level.customerDishesSequence)
    : [];
  // The RECORDED sequence is what the editor shows — the instruction, not the
  // outcome. A level with customers but no recorded sequence gets one Auto
  // entry per customer, which is what "the curve decides all of them" looks
  // like written down.
  const initialCounts = storedCounts.length
    ? storedCounts
    : existing.length
      ? existing.map((c) => (c.typeId === 1 ? -1 : 0))
      : [...DEFAULT_DISH_COUNT_SEQUENCE];
  /** What each customer currently orders — shown as a badge beside its field. */
  const actualCounts = existing.map((c) => c.dishes.length);

  const storedWeights = parseWeightSet(deps.level.ingredientWeights ?? "");
  const initialWeights: WeightSet =
    storedWeights.ingredients.size > 0
      ? storedWeights
      : {
          ingredients: new Map(
            deps.projected.map.cookedIngredients.map((c) => [c.id, DEFAULT_INGREDIENT_WEIGHT]),
          ),
          composites: storedWeights.composites,
        };

  /**
   * Which fields the level ALREADY records, and which the designer touched here.
   *
   * The dialog has to show something for a field a level does not set, so it
   * shows a sensible default — but writing that default back on Generate is
   * what turns "the generator decides this" into "it is pinned to the dialog's
   * placeholder". That is not a cosmetic difference: an untouched weight grid
   * would pin every ingredient at 100, and an untouched dish list would pin
   * three customers, instead of letting the pipeline roll the ranges the config
   * bar configures. So each field is written back only if it was already there
   * or the designer actually moved it.
   */
  const had = {
    weights: Boolean(deps.level.ingredientWeights),
    counts: Boolean(deps.level.customerDishesSequence),
    curve: Boolean(deps.level.complexityCurve),
  };
  const touched = { weights: false, counts: false, curve: false };

  let dishCounts = [...initialCounts];
  // Existing customers ARE an authored sequence, even though the level may not
  // record one — the dialog opened showing their dish counts, and generating
  // would otherwise silently replace them with a rolled sequence.
  const countsFromExisting = existing.length > 0;
  let curveState = deps.level.complexityCurve
    ? parseCurve(deps.level.complexityCurve, cachedCurve ?? defaultCurve(1, DEFAULT_MAX_DISH_SLOTS))
    : cachedCurve
      ? structuredClone(cachedCurve)
      : defaultCurve(1, DEFAULT_MAX_DISH_SLOTS);

  const weightEditor = createDishWeightEditor({
    projected: deps.projected,
    ix: deps.ix,
    ids: deps.ids,
    initial: initialWeights,
    onChange: () => (touched.weights = true),
  });

  // The obstacle budget is authored, not rolled, so the dialog edits the
  // level's own record and writes it straight back — same as the weights.
  const obstacles = createObstacleEditor({
    initial: parseObstacles(deps.level.obstacleData),
    gridCells: deps.ix.doc.map.gridWidth * deps.ix.doc.map.gridHeight,
  });

  const seedInput = el("input", {
    type: "number",
    min: "0",
    step: "1",
    placeholder: "auto",
    value: deps.level.randomSeed === undefined ? "" : String(deps.level.randomSeed),
  }) as HTMLInputElement;
  seedInput.title =
    "Every random draw comes from this seed, so the same seed rebuilds the same level. " +
    "Leave it blank to let the generator pick one — it will try several until the level is winnable, " +
    "then write the winning one back here.";

  /**
   * One collapsible section. Open by default, every one of them: the dialog is
   * a checklist of what a generate will use, and a designer who opens it to
   * check one number should not have to expand four things to find it. The
   * folds are for getting long sections OUT of the way once you know what they
   * hold, not for hiding them until asked.
   */
  const section = (title: string, body: (Node | string)[]): HTMLElement =>
    el("details", { class: "generate-section", open: "" }, [
      el("summary", {}, [title]),
      el("div", { class: "generate-section-body" }, body),
    ]);

  const panel = el("div", { class: "auto-generate-panel auto-generate-sheet" }, [
    section("Customers (dish count per customer — -1 = Staff, 0 = Auto)", [
      dishCountEditor(initialCounts, (next) => {
        dishCounts = next;
        touched.counts = true;
      }, actualCounts),
    ]),
    section("Generator Weights", [weightEditor.element]),
    section("Complexity Curve (total ingredients per customer, by normalized order position)", [
      createCurveWithPresets(curveState, (next) => {
        curveState = next;
        cachedCurve = next;
        touched.curve = true;
      }),
    ]),
    section("Obstacles", [obstacles.element]),
    section("Random Seed", [el("label", { class: "field" }, ["Seed (blank = pick one)", seedInput])]),
    el("p", { class: "muted" }, [
      "Each dish picks an orderable first, then fills its slots — so every generated dish is " +
        "well-formed by construction, respects each slot's cap, and fills a required topping. " +
        "The ingredient queue is generated from the resulting orders and verified with the difficulty " +
        "estimator; if the level cannot be won, the shuffle distance is lowered a step at a time and, " +
        "failing that, another seed is tried.",
    ]),
    el("div", { class: "auto-generate-actions" }, [
      button("Cancel", close),
      // Two buttons rather than a checkbox, because they are two different
      // requests and the difference matters. Plain Generate honours a pinned
      // seed absolutely — if that seed cannot make a playable level, it says
      // so. "Generate until valid" says the designer wants a working level more
      // than they want that exact number, and walks upward from it. Only they
      // can decide which, so it is never inferred.
      button("🎲 Generate until valid", (event) => run(event, true), {
        class: "generate-until-valid",
        title:
          "Keep walking the seed upward until a level passes both the difficulty estimate and the " +
          "deadlock audit. Starts from the seed above when one is set, otherwise from a fresh one.",
      }),
      button("Generate", (event) => run(event, false), { class: "primary" }),
    ]),
  ]);

  /** Shared by both buttons — they differ only in whether the seed may move. */
  function run(event: MouseEvent, searchFromSeed: boolean): void {
    if (
      deps.currentCustomers().length > 0 &&
      !confirm("Auto-generate replaces every customer AND the whole queue in this level. Continue?")
    ) {
      return;
    }
    // The pipeline reads its inputs off the level, so the dialog's job is to
    // record what the designer chose and then hand over.
    if (had.weights || touched.weights) {
      deps.level.ingredientWeights = serializeWeightSet(weightEditor.weights);
    }
    if (had.counts || touched.counts || countsFromExisting) {
      deps.level.customerDishesSequence = serializeDishCountSequence(dishCounts);
    }
    if (had.curve || touched.curve) {
      deps.level.complexityCurve = serializeCurve(curveState);
    }
    deps.level.obstacleData = serializeObstacles(obstacles.config);
    const seed = seedInput.value.trim();
    if (seed === "") delete deps.level.randomSeed;
    else deps.level.randomSeed = Math.max(0, Math.trunc(Number(seed) || 0)) >>> 0;

    // A full pipeline run is seconds of straight-line work — and a seed search
    // is many of them — so paint a busy label before starting: a click that
    // looks like it did nothing is worse than a wait. The timer (not rAF) is
    // deliberate; rAF never fires in a hidden tab.
    const btn = event.currentTarget as HTMLButtonElement;
    const label = btn.textContent;
    btn.textContent = searchFromSeed ? "Searching…" : "Generating…";
    btn.disabled = true;
    setTimeout(() => {
      const result = generateLevel(
        deps.level,
        {
          ix: deps.ix,
          ids: deps.ids,
          projected: deps.projected,
          ...(deps.scenario ? { scenario: deps.scenario } : {}),
        },
        // How big a generated level may be is a project-wide setting, edited in
        // Level Path's config bar. Reading it here rather than duplicating the
        // control keeps one answer to the question.
        { bounds: loadConfig().bounds, ...(searchFromSeed ? { searchFromSeed: true } : {}) },
      );
      btn.textContent = label;
      btn.disabled = false;
      deps.onGenerated(result);
      close();
      const notes = [...result.errors, ...result.warnings];
      if (result.ok && searchFromSeed && result.seedsTried > 1) {
        notes.unshift(`Walked ${result.seedsTried} seeds to find one that works; settled on ${result.seed}.`);
      }
      if (notes.length > 0) {
        alert(`${result.ok ? "Generated with notes" : "Generate failed"}:\n\n${notes.join("\n")}`);
      }
    }, 0);
  }

  const overlay = el("div", { class: "overlay-panel" }, [
    el("div", { class: "definitions-head" }, [
      el("h2", {}, ["Auto Generate Level"]),
      button("✕ Close", close, { class: "primary" }),
    ]),
    panel,
  ]);
  overlay.addEventListener("click", (e) => {
    if (e.target === overlay) close();
  });
  document.body.append(overlay);
}
