// "Auto Generate" popup — Customer section header button (see
// customerSection.ts). Collects a dish-count-per-customer list, an
// allowed-ingredients toggle grid, and a complexity curve, then hands them to
// generateCustomers() (autoGenerate.ts) and replaces the whole customer list
// with the result.

import Sortable from "sortablejs";
import { CUSTOMER_STAFF } from "../../core/effects.ts";
import type { CustomerConfig, Id, MapDef } from "../../core/types.ts";
import { showContextMenu } from "../contextMenu.ts";
import { button, el } from "../dom.ts";
import { cookedIconEl } from "../icon.ts";
import { DEFAULT_MAX_DISH_SLOTS, generateCustomers } from "./autoGenerate.ts";
import { createCurveEditor, defaultCurve } from "./curveEditor.ts";
import type { CurveState } from "./curveEditor.ts";

export interface AutoGenerateDeps {
  map: MapDef;
  currentCustomers(): CustomerConfig[];
  onGenerate(customers: CustomerConfig[]): void;
}

function dishCountEditor(initial: number[], onChange: (counts: number[]) => void): HTMLElement {
  let counts = initial.length ? [...initial] : [1, 1, 1];
  const wrap = el("div", { class: "dish-count-wrap" });
  let listEl: HTMLElement | null = null;

  const renderList = () => {
    const next = el("div", { class: "dish-count-list" });
    counts.forEach((count, i) => {
      const item = el("div", { class: `dish-count-item${count === 0 ? " staff" : ""}` });
      const input = el("input", { type: "number", min: "0", value: String(count) }) as HTMLInputElement;
      input.title = "Number of dishes this customer orders — 0 = Staff (clears a dirty stack instead)";
      input.addEventListener("change", () => {
        counts[i] = Math.max(0, Number(input.value) || 0);
        item.classList.toggle("staff", counts[i] === 0);
        onChange(counts);
      });
      const remove = button("✕", (e) => {
        e.stopPropagation();
        counts.splice(i, 1);
        renderList();
        onChange(counts);
      }, { class: "dish-count-remove", title: "Remove" });
      item.append(input, remove);
      item.addEventListener("contextmenu", (e) => {
        showContextMenu(
          e,
          [
            { label: "Insert Before", onSelect: () => { counts.splice(i, 0, 1); renderList(); onChange(counts); } },
            { label: "Insert After", onSelect: () => { counts.splice(i + 1, 0, 1); renderList(); onChange(counts); } },
            { label: "Remove", danger: true, separator: true, onSelect: () => { counts.splice(i, 1); renderList(); onChange(counts); } },
          ],
          { title: `Customer ${i + 1}` },
        );
      });
      next.append(item);
    });

    const addBtn = el("div", { class: "dish-count-item add" }, ["＋"]);
    addBtn.addEventListener("click", () => {
      counts.push(1);
      renderList();
      onChange(counts);
    });
    next.append(addBtn);

    Sortable.create(next, {
      animation: 150,
      draggable: ".dish-count-item:not(.add)",
      onEnd: (evt) => {
        if (evt.oldIndex === undefined || evt.newIndex === undefined) return;
        if (evt.oldIndex === evt.newIndex) return;
        const [moved] = counts.splice(evt.oldIndex, 1);
        counts.splice(Math.min(evt.newIndex, counts.length), 0, moved);
        renderList();
        onChange(counts);
      },
    });

    if (listEl) listEl.replaceWith(next);
    else wrap.append(next);
    listEl = next;
  };

  renderList();
  return wrap;
}

function ingredientToggleGrid(
  map: MapDef,
  initiallyOn: Set<Id>,
  onChange: (ids: Set<Id>) => void,
): HTMLElement {
  const enabled = new Set(initiallyOn);
  const grid = el("div", { class: "ctx-picker ingredient-toggle-grid" });
  for (const c of map.cookedIngredients) {
    const cell = el("button", { class: "ctx-pick", title: c.name }) as HTMLButtonElement;
    cell.classList.toggle("toggle-off", !enabled.has(c.id));
    cell.append(cookedIconEl(c.id, 64));
    cell.addEventListener("click", () => {
      if (enabled.has(c.id)) enabled.delete(c.id);
      else enabled.add(c.id);
      cell.classList.toggle("toggle-off", !enabled.has(c.id));
      onChange(enabled);
    });
    grid.append(cell);
  }
  return grid;
}

/**
 * Remembers the last-edited curve across dialog opens (any level) — a
 * module-level singleton, not level data, so it deliberately outlives any
 * one CustomerSection instance (which gets recreated on every level switch).
 */
let cachedCurve: CurveState | null = null;

export function openAutoGenerateDialog(deps: AutoGenerateDeps): void {
  const close = () => overlay.remove();

  const existing = deps.currentCustomers();
  const initialCounts = existing.length
    ? existing.map((c) => (c.typeId === CUSTOMER_STAFF ? 0 : c.dishes.length))
    : [1, 1, 1];

  let dishCounts = [...initialCounts];
  let allowedIds = new Set(deps.map.cookedIngredients.map((c) => c.id));
  const curve = cachedCurve ? structuredClone(cachedCurve) : defaultCurve(1, DEFAULT_MAX_DISH_SLOTS);
  let curveState = curve;

  const panel = el("div", { class: "auto-generate-panel" }, [
    el("h3", {}, ["Customers (dish count per customer — 0 = Staff)"]),
    dishCountEditor(initialCounts, (next) => (dishCounts = next)),
    el("h3", {}, ["Allowed Ingredients"]),
    ingredientToggleGrid(deps.map, allowedIds, (next) => (allowedIds = next)),
    el("h3", {}, ["Complexity Curve (total ingredients per customer, by normalized order position)"]),
    createCurveEditor(curve, (next) => {
      curveState = next;
      cachedCurve = next;
    }),
    el("div", { class: "auto-generate-actions" }, [
      button("Cancel", close),
      button(
        "Generate",
        () => {
          if (deps.currentCustomers().length > 0 && !confirm("Auto-generate replaces every customer in this level. Continue?")) {
            return;
          }
          deps.onGenerate(generateCustomers(deps.map, { dishCounts, allowedCookedIds: allowedIds, curve: curveState }));
          close();
        },
        { class: "primary" },
      ),
    ]),
  ]);

  const overlay = el("div", { class: "overlay-panel" }, [
    el("div", { class: "definitions-head" }, [
      el("h2", {}, ["Auto Generate Customers"]),
      button("✕ Close", close, { class: "primary" }),
    ]),
    panel,
  ]);
  overlay.addEventListener("click", (e) => {
    if (e.target === overlay) close();
  });
  document.body.append(overlay);
}
