// Pure "Auto Generate" customer-sequence logic — kept free of any DOM/UI
// import (no contextMenu.ts, no dom.ts) so it can be unit tested under
// Vitest's default node environment. The popup UI that collects
// GenerateOptions from the designer lives in autoGenerateDialog.ts.

import { CUSTOMER_STAFF } from "../../core/effects.ts";
import type { CookedIngredientDef, CustomerConfig, Id, MapDef } from "../../core/types.ts";
import type { CurveState } from "./curveEditor.ts";
import { evaluateCurve } from "./curveEditor.ts";

/** Hard ceiling on any one dish's ingredient count, so a spiky curve can't produce absurd dishes. */
export const DEFAULT_MAX_DISH_SLOTS = 5;
/** Three generated customers, each letting the complexity curve choose its dish count. */
export const DEFAULT_DISH_COUNT_SEQUENCE = [0, 0, 0] as const;

export interface GenerateOptions {
  /**
   * One entry per customer to create, in order. -1 = a Staff customer (no
   * dishes). 0 = Auto — the dish count is derived from the complexity
   * curve's target for that customer instead of being fixed (see
   * `autoDishCount`). Any positive value is an explicit dish count.
   */
  dishCounts: number[];
  /** Cooked ingredient id -> selection weight (0-100). 0/absent = excluded entirely. */
  ingredientWeights: Map<Id, number>;
  curve: CurveState;
  maxDishSlots?: number;
  /** Injectable for deterministic tests; defaults to Math.random. */
  random?: () => number;
}

/** "3;1;-1" -> [3,1,-1] (dish count per customer; -1 = Staff, 0 = Auto). Non-numeric tokens fall back to 0 (Auto). */
export function parseDishCountSequence(s: string): number[] {
  if (!s || !s.trim()) return [];
  return s.split(";").map((t) => Math.max(-1, Number(t) || 0));
}

/**
 * Chooses a dish count for an "Auto" (0) customer from the curve's target
 * total ingredient count — aiming for dishes around the middle of the
 * possible 1..maxSlots range, so a big target becomes several
 * medium-sized dishes rather than one dish or `target` tiny ones.
 */
export function autoDishCount(target: number, maxSlots: number): number {
  const avgDishSize = (1 + maxSlots) / 2;
  return Math.max(1, Math.round(target / avgDishSize));
}

export function serializeDishCountSequence(counts: number[]): string {
  return counts.join(";");
}

/** Picks one item, biased by weight — a single rand() draw consumed as a position along the cumulative weight sum. */
function weightedPick<T>(items: T[], weightOf: (t: T) => number, rand: () => number): T | undefined {
  const weighted = items.map((t) => ({ t, w: Math.max(0, weightOf(t)) })).filter((x) => x.w > 0);
  const total = weighted.reduce((sum, x) => sum + x.w, 0);
  if (total <= 0) return undefined;
  let r = rand() * total;
  for (const x of weighted) {
    r -= x.w;
    if (r <= 0) return x.t;
  }
  return weighted[weighted.length - 1].t;
}

function followersOf(toppings: CookedIngredientDef[], baseId: Id): CookedIngredientDef[] {
  return toppings.filter((t) => {
    const req = t.baseId;
    return Array.isArray(req) ? req.includes(baseId) : req === baseId;
  });
}

function requiresBase(topping: CookedIngredientDef, baseId: Id): boolean {
  const req = topping.baseId;
  return Array.isArray(req) ? req.includes(baseId) : req === baseId;
}

/**
 * Best-effort pass so a later Auto-Generate Queue run can cover every dish
 * with zero leftover pieces: a tool recipe can yield several pieces per raw
 * pickup (1 tomato → 2 slices), so if the total demand for a topping isn't a
 * clean multiple of its yield, the last pickup would produce a piece nobody
 * ordered — dead weight sitting on the table at the end of the level. This
 * tops the total up to the next multiple by adding the topping into other
 * dishes that already have a compatible base, room for one more ingredient,
 * and don't already contain it (so no dish repeats an ingredient). Bases
 * aren't touched — a base is one per dish, so "adding one more" would mean
 * inventing a whole new dish, out of scope for a best-effort nudge. If there's
 * nowhere left to add one, the remainder is simply left as-is.
 */
function topUpPieceAlignment(map: MapDef, customers: CustomerConfig[], maxSlots: number): void {
  const yieldByCooked = new Map<Id, number>();
  for (const tool of map.tools) {
    for (const recipe of tool.recipes) yieldByCooked.set(recipe.out, recipe.amount);
  }

  const totals = new Map<Id, number>();
  for (const c of customers) {
    for (const d of c.dishes) {
      for (const id of d.cookedIds) totals.set(id, (totals.get(id) ?? 0) + 1);
    }
  }

  for (const [cookedId, total] of totals) {
    const amount = yieldByCooked.get(cookedId) ?? 1;
    if (amount <= 1) continue;
    const remainder = total % amount;
    if (remainder === 0) continue;
    const topping = map.cookedIngredients.find((c) => c.id === cookedId);
    if (!topping || topping.baseId === undefined) continue; // bases are out of scope — see above

    let need = amount - remainder;
    for (const c of customers) {
      if (need <= 0) break;
      for (const d of c.dishes) {
        if (need <= 0) break;
        if (d.cookedIds.length === 0 || d.cookedIds.length >= maxSlots) continue;
        if (d.cookedIds.includes(cookedId)) continue;
        if (!requiresBase(topping, d.cookedIds[0])) continue;
        d.cookedIds.push(cookedId);
        need--;
      }
    }
  }
}

/**
 * Generates a full customer sequence.
 *
 * Per customer: the curve is sampled at the customer's normalized position
 * (index / (count-1), mapped into the curve's own X range) to get a target
 * total ingredient count, randomly split across that customer's dishes (each
 * dish starts at 1, then leftover "extra" ingredient slots are handed out to
 * random dishes one at a time, capped at `maxDishSlots` each).
 *
 * Per dish: cooked ingredients with a nonzero weight split into "base" (no
 * `baseId`) and "topping" (has one), and every pick (base or follower) is
 * weighted-random rather than uniform — see `weightedPick`. A base's
 * *capacity* is 1 (itself) plus how many allowed toppings require it — the
 * biggest dish it could ever fill. Map1's
 * Soda Cup has capacity 2 (itself + Ice, its only follower): a 1-slot dish
 * always gets a capacity-2-or-less base first (it can't use a topping
 * anyway, so reserve the "big" bases like Bun/Chicken for bigger dishes); a
 * 2-slot dish can still use Soda Cup (Cup+Ice fills it exactly); a 3+-slot
 * dish excludes it (nowhere left to go after Cup+Ice) in favor of a base
 * whose capacity can actually reach the target. Whichever base is picked,
 * remaining slots fill with random distinct followers of it (fewer than
 * requested if it doesn't have enough distinct followers — this is a random
 * approximation of the curve, not an exact fit).
 *
 * After every customer is built, `topUpPieceAlignment` makes a best-effort
 * pass to round each topping's total demand up to a clean multiple of its
 * tool recipe's yield, so a later Auto-Generate Queue run has no leftover
 * pieces on the table at the end of the level.
 */
export function generateCustomers(map: MapDef, opts: GenerateOptions): CustomerConfig[] {
  const rand = opts.random ?? Math.random;
  const maxSlots = Math.max(1, opts.maxDishSlots ?? DEFAULT_MAX_DISH_SLOTS);
  const n = opts.dishCounts.length;

  const weightOf = (c: CookedIngredientDef) => opts.ingredientWeights.get(c.id) ?? 0;
  const cooked = map.cookedIngredients.filter((c) => weightOf(c) > 0);
  const bases = cooked.filter((c) => c.baseId === undefined);
  const toppings = cooked.filter((c) => c.baseId !== undefined);
  const capacity = (base: CookedIngredientDef) => followersOf(toppings, base.id).length + 1;

  function generateDish(slotTarget: number): Id[] {
    const k = Math.max(1, slotTarget);
    const pool =
      k === 1
        ? bases.filter((b) => capacity(b) <= 2) // reserve "weak" bases for 1-slot dishes...
        : bases.filter((b) => capacity(b) >= k); // ...and only "strong enough" bases for the rest
    const base = weightedPick(pool.length ? pool : bases, weightOf, rand);
    if (!base) return [];
    const dish = [base.id];
    const followerPool = followersOf(toppings, base.id);
    while (dish.length < k && followerPool.length > 0) {
      const picked = weightedPick(followerPool, weightOf, rand);
      if (!picked) break;
      dish.push(picked.id);
      followerPool.splice(followerPool.indexOf(picked), 1);
    }
    return dish;
  }

  /** Splits `total` across `count` slots, each starting at 1, extras handed out randomly up to maxSlots each. */
  function distribute(total: number, count: number): number[] {
    const slots = new Array(count).fill(1);
    let remaining = Math.max(0, total - count);
    let guard = 10000;
    while (remaining > 0 && guard-- > 0) {
      if (slots.every((s) => s >= maxSlots)) break;
      const i = Math.floor(rand() * count);
      if (slots[i] < maxSlots) {
        slots[i]++;
        remaining--;
      }
    }
    return slots;
  }

  const customers: CustomerConfig[] = [];
  for (let i = 0; i < n; i++) {
    const configured = opts.dishCounts[i];
    if (configured === -1) {
      customers.push({ typeId: CUSTOMER_STAFF, waitTime: 0, weatherEff: 0, dishes: [] });
      continue;
    }
    const normX = n > 1 ? i / (n - 1) : 0;
    const realX = opts.curve.range.minX + normX * (opts.curve.range.maxX - opts.curve.range.minX);
    const target = Math.round(evaluateCurve(opts.curve, realX));
    const dishCount = configured === 0 ? autoDishCount(target, maxSlots) : configured;
    const total = Math.max(dishCount, Math.min(dishCount * maxSlots, target));
    const slots = distribute(total, dishCount);
    customers.push({
      typeId: 0,
      waitTime: 0,
      weatherEff: 0,
      dishes: slots.map((k) => ({ cookedIds: generateDish(k), effects: [] })),
    });
  }
  topUpPieceAlignment(map, customers, maxSlots);
  return customers;
}
