// Pure "Auto Generate" customer-sequence logic — kept free of any DOM/UI
// import (no contextMenu.ts, no dom.ts) so it can be unit tested under
// Vitest's default node environment. The popup UI that collects
// GenerateOptions from the designer lives in autoGenerateDialog.ts.

import { CUSTOMER_STAFF } from "../../core/effects.ts";
import type { CookedIngredientDef, CustomerConfig, Id, MapDef } from "../../core/types.ts";
import type { CurveState } from "./curveEditor.ts";
import { evaluateCurve } from "./curveEditor.ts";

/** Hard ceiling on any one dish's ingredient count, so a spiky curve can't produce absurd dishes. */
export const DEFAULT_MAX_DISH_SLOTS = 5;

export interface GenerateOptions {
  /** One entry per customer to create, in order. 0 = a Staff customer (no dishes). */
  dishCounts: number[];
  allowedCookedIds: Set<Id>;
  curve: CurveState;
  maxDishSlots?: number;
  /** Injectable for deterministic tests; defaults to Math.random. */
  random?: () => number;
}

function followersOf(toppings: CookedIngredientDef[], baseId: Id): CookedIngredientDef[] {
  return toppings.filter((t) => {
    const req = t.baseId;
    return Array.isArray(req) ? req.includes(baseId) : req === baseId;
  });
}

/**
 * Generates a full customer sequence.
 *
 * Per customer: the curve is sampled at the customer's normalized position
 * (index / (count-1), mapped into the curve's own X range) to get a target
 * total ingredient count, randomly split across that customer's dishes (each
 * dish starts at 1, then leftover "extra" ingredient slots are handed out to
 * random dishes one at a time, capped at `maxDishSlots` each).
 *
 * Per dish: allowed cooked ingredients split into "base" (no `baseId`) and
 * "topping" (has one). A base's *capacity* is 1 (itself) plus how many
 * allowed toppings require it — the biggest dish it could ever fill. Map1's
 * Soda Cup has capacity 2 (itself + Ice, its only follower): a 1-slot dish
 * always gets a capacity-2-or-less base first (it can't use a topping
 * anyway, so reserve the "big" bases like Bun/Chicken for bigger dishes); a
 * 2-slot dish can still use Soda Cup (Cup+Ice fills it exactly); a 3+-slot
 * dish excludes it (nowhere left to go after Cup+Ice) in favor of a base
 * whose capacity can actually reach the target. Whichever base is picked,
 * remaining slots fill with random distinct followers of it (fewer than
 * requested if it doesn't have enough distinct followers — this is a random
 * approximation of the curve, not an exact fit).
 */
export function generateCustomers(map: MapDef, opts: GenerateOptions): CustomerConfig[] {
  const rand = opts.random ?? Math.random;
  const maxSlots = Math.max(1, opts.maxDishSlots ?? DEFAULT_MAX_DISH_SLOTS);
  const n = opts.dishCounts.length;

  const cooked = map.cookedIngredients.filter((c) => opts.allowedCookedIds.has(c.id));
  const bases = cooked.filter((c) => c.baseId === undefined);
  const toppings = cooked.filter((c) => c.baseId !== undefined);
  const capacity = (base: CookedIngredientDef) => followersOf(toppings, base.id).length + 1;

  const pickRandom = <T,>(arr: T[]): T | undefined =>
    arr.length === 0 ? undefined : arr[Math.floor(rand() * arr.length)];

  function generateDish(slotTarget: number): Id[] {
    const k = Math.max(1, slotTarget);
    const pool =
      k === 1
        ? bases.filter((b) => capacity(b) <= 2) // reserve "weak" bases for 1-slot dishes...
        : bases.filter((b) => capacity(b) >= k); // ...and only "strong enough" bases for the rest
    const base = pickRandom(pool.length ? pool : bases);
    if (!base) return [];
    const dish = [base.id];
    const followerPool = followersOf(toppings, base.id);
    while (dish.length < k && followerPool.length > 0) {
      const i = Math.floor(rand() * followerPool.length);
      dish.push(followerPool[i].id);
      followerPool.splice(i, 1);
    }
    return dish;
  }

  /** Splits `total` across `count` slots, each starting at 1, extras handed out randomly up to maxSlots each. */
  function distribute(total: number, count: number): number[] {
    const slots = new Array(count).fill(1);
    let remaining = Math.max(0, total - count);
    let guard = 10000;
    while (remaining > 0 && guard-- > 0) {
      if (slots.every((s) => s >= maxSlots)) break;
      const i = Math.floor(rand() * count);
      if (slots[i] < maxSlots) {
        slots[i]++;
        remaining--;
      }
    }
    return slots;
  }

  const customers: CustomerConfig[] = [];
  for (let i = 0; i < n; i++) {
    const dishCount = opts.dishCounts[i];
    if (dishCount <= 0) {
      customers.push({ typeId: CUSTOMER_STAFF, waitTime: 0, weatherEff: 0, dishes: [] });
      continue;
    }
    const normX = n > 1 ? i / (n - 1) : 0;
    const realX = opts.curve.range.minX + normX * (opts.curve.range.maxX - opts.curve.range.minX);
    const target = Math.round(evaluateCurve(opts.curve, realX));
    const total = Math.max(dishCount, Math.min(dishCount * maxSlots, target));
    const slots = distribute(total, dishCount);
    customers.push({
      typeId: 0,
      waitTime: 0,
      weatherEff: 0,
      dishes: slots.map((k) => ({ cookedIds: generateDish(k), effects: [] })),
    });
  }
  return customers;
}
