// "Auto Generate" popup — Customer section header button (see
// customerSection.ts). Collects a dish-count-per-customer list, an
// ingredient weight grid, and a complexity curve, then hands them to
// generateCustomers() (autoGenerate.ts) and replaces the whole customer list
// with the result. The three inputs are also written back into deps.level
// (ingredientWeights/customerDishesSequence/complexityCurve) so the Customer
// section's read-only fields stay in sync with whatever last generated the
// list — see customerSection.ts's level-params bar.

import Sortable from "sortablejs";
import { CUSTOMER_STAFF } from "../../core/effects.ts";
import type { CustomerConfig, Id, MapDef } from "../../core/types.ts";
import type { LevelData } from "../../data/mapLoader.ts";
import { showContextMenu } from "../contextMenu.ts";
import { button, el } from "../dom.ts";
import {
  DEFAULT_DISH_COUNT_SEQUENCE,
  DEFAULT_MAX_DISH_SLOTS,
  generateCustomers,
  parseDishCountSequence,
  serializeDishCountSequence,
} from "./autoGenerate.ts";
import { createCurveWithPresets, defaultCurve, parseCurve, serializeCurve } from "./curveEditor.ts";
import type { CurveState } from "./curveEditor.ts";
import {
  createIngredientWeightGrid,
  DEFAULT_INGREDIENT_WEIGHT,
  parseIngredientWeights,
  serializeIngredientWeights,
} from "./ingredientWeightEditor.ts";

export interface AutoGenerateDeps {
  map: MapDef;
  level: LevelData;
  currentCustomers(): CustomerConfig[];
  onGenerate(customers: CustomerConfig[]): void;
}

export function dishCountEditor(initial: number[], onChange: (counts: number[]) => void): HTMLElement {
  let counts = initial.length ? [...initial] : [1, 1, 1];
  const wrap = el("div", { class: "dish-count-wrap" });
  let listEl: HTMLElement | null = null;

  const renderList = () => {
    const next = el("div", { class: "dish-count-list" });
    counts.forEach((count, i) => {
      const item = el("div", {
        class: `dish-count-item${count === -1 ? " staff" : count === 0 ? " auto" : ""}`,
      });
      const input = el("input", { type: "number", min: "-1", value: String(count) }) as HTMLInputElement;
      input.title =
        "Number of dishes this customer orders — -1 = Staff (clears a dirty stack instead), 0 = Auto (derived from the complexity curve)";
      input.addEventListener("change", () => {
        counts[i] = Math.max(-1, Number(input.value) || 0);
        item.classList.toggle("staff", counts[i] === -1);
        item.classList.toggle("auto", counts[i] === 0);
        onChange(counts);
      });
      const remove = button("✕", (e) => {
        e.stopPropagation();
        counts.splice(i, 1);
        renderList();
        onChange(counts);
      }, { class: "dish-count-remove", title: "Remove" });
      item.append(input, remove);
      item.addEventListener("contextmenu", (e) => {
        showContextMenu(
          e,
          [
            { label: "Insert Before", onSelect: () => { counts.splice(i, 0, 0); renderList(); onChange(counts); } },
            { label: "Insert After", onSelect: () => { counts.splice(i + 1, 0, 0); renderList(); onChange(counts); } },
            { label: "Remove", danger: true, separator: true, onSelect: () => { counts.splice(i, 1); renderList(); onChange(counts); } },
          ],
          { title: `Customer ${i + 1}` },
        );
      });
      next.append(item);
    });

    const addBtn = el("div", { class: "dish-count-item add" }, ["＋"]);
    addBtn.addEventListener("click", () => {
      counts.push(0);
      renderList();
      onChange(counts);
    });
    next.append(addBtn);

    Sortable.create(next, {
      animation: 150,
      draggable: ".dish-count-item:not(.add)",
      onEnd: (evt) => {
        if (evt.oldIndex === undefined || evt.newIndex === undefined) return;
        if (evt.oldIndex === evt.newIndex) return;
        const [moved] = counts.splice(evt.oldIndex, 1);
        counts.splice(Math.min(evt.newIndex, counts.length), 0, moved);
        renderList();
        onChange(counts);
      },
    });

    if (listEl) listEl.replaceWith(next);
    else wrap.append(next);
    listEl = next;
  };

  renderList();
  return wrap;
}

/**
 * Every cooked id already used by this level's customers — the Auto Generate
 * dialog's default allowlist, so re-running it on an already-authored level
 * keeps using the same ingredient palette instead of throwing every item in
 * the map back in. Empty (never-generated) levels fall back to "everything
 * allowed" — there's nothing to infer a palette from yet.
 */
function usedCookedIds(customers: CustomerConfig[]): Set<Id> {
  const ids = new Set<Id>();
  for (const c of customers) for (const d of c.dishes) for (const id of d.cookedIds) ids.add(id);
  return ids;
}

/**
 * Remembers the last-edited curve across dialog opens (any level) — a
 * module-level singleton, not level data, so it deliberately outlives any
 * one CustomerSection instance (which gets recreated on every level switch).
 */
let cachedCurve: CurveState | null = null;

export function openAutoGenerateDialog(deps: AutoGenerateDeps): void {
  const close = () => overlay.remove();

  const existing = deps.currentCustomers();
  const storedCounts = deps.level.customerDishesSequence
    ? parseDishCountSequence(deps.level.customerDishesSequence)
    : [];
  const initialCounts = existing.length
    ? existing.map((c) => (c.typeId === CUSTOMER_STAFF ? -1 : c.dishes.length))
    : storedCounts.length
      ? storedCounts
      : [...DEFAULT_DISH_COUNT_SEQUENCE];

  const used = usedCookedIds(existing);
  const storedWeights = deps.level.ingredientWeights ? parseIngredientWeights(deps.level.ingredientWeights) : null;
  let ingredientWeights =
    storedWeights && storedWeights.size > 0
      ? storedWeights
      : used.size > 0
        ? new Map([...used].map((id) => [id, DEFAULT_INGREDIENT_WEIGHT]))
        : new Map(deps.map.cookedIngredients.map((c) => [c.id, DEFAULT_INGREDIENT_WEIGHT]));

  let dishCounts = [...initialCounts];
  let curveState = deps.level.complexityCurve
    ? parseCurve(deps.level.complexityCurve, cachedCurve ?? defaultCurve(1, DEFAULT_MAX_DISH_SLOTS))
    : cachedCurve
      ? structuredClone(cachedCurve)
      : defaultCurve(1, DEFAULT_MAX_DISH_SLOTS);

  const weightGrid = createIngredientWeightGrid(deps.map, ingredientWeights, (next) => (ingredientWeights = next));

  const panel = el("div", { class: "auto-generate-panel" }, [
    el("h3", {}, ["Customers (dish count per customer — -1 = Staff, 0 = Auto)"]),
    dishCountEditor(initialCounts, (next) => (dishCounts = next)),
    el("h3", {}, ["Ingredient Weights"]),
    el("div", { class: "ingredient-toggle-actions" }, [
      button("Enable All", () => weightGrid.setAll(DEFAULT_INGREDIENT_WEIGHT), { class: "small-btn" }),
      button("Disable All", () => weightGrid.setAll(0), { class: "small-btn" }),
    ]),
    weightGrid.element,
    el("h3", {}, ["Complexity Curve (total ingredients per customer, by normalized order position)"]),
    createCurveWithPresets(curveState, (next) => {
      curveState = next;
      cachedCurve = next;
    }),
    el("div", { class: "auto-generate-actions" }, [
      button("Cancel", close),
      button(
        "Generate",
        () => {
          if (deps.currentCustomers().length > 0 && !confirm("Auto-generate replaces every customer in this level. Continue?")) {
            return;
          }
          deps.level.ingredientWeights = serializeIngredientWeights(ingredientWeights);
          deps.level.customerDishesSequence = serializeDishCountSequence(dishCounts);
          deps.level.complexityCurve = serializeCurve(curveState);
          deps.onGenerate(generateCustomers(deps.map, { dishCounts, ingredientWeights, curve: curveState }));
          close();
        },
        { class: "primary" },
      ),
    ]),
  ]);

  const overlay = el("div", { class: "overlay-panel" }, [
    el("div", { class: "definitions-head" }, [
      el("h2", {}, ["Auto Generate Customers"]),
      button("✕ Close", close, { class: "primary" }),
    ]),
    panel,
  ]);
  overlay.addEventListener("click", (e) => {
    if (e.target === overlay) close();
  });
  document.body.append(overlay);
}
