// "Auto Generate" popup — Ingredient Queue section header button (see
// queueSection.ts). Lets the post-fill shuffle step be either a single fixed
// displacement distance or a per-position curve (same curve editor widget as
// the Customer Auto Generate dialog) — see queueGenerate.ts's
// ShuffleRangeSpec for how each mode is consumed. Curve mode is also written
// back into deps.level.shuffleCurve so the Queue section's read-only field
// stays in sync — see queueSection.ts's shuffle-curve bar.

import type { LevelData } from "../../data/mapLoader.ts";
import { button, el } from "../dom.ts";
import { createCurveWithPresets, defaultCurve, parseCurve, serializeCurve } from "./curveEditor.ts";
import type { CurveState } from "./curveEditor.ts";
import type { ShuffleRangeSpec } from "./queueGenerate.ts";

export interface AutoGenerateQueueDeps {
  level: LevelData;
  onGenerate(spec: ShuffleRangeSpec): void;
}

/**
 * Remembers the last-edited curve across dialog opens — a module-level
 * singleton, same pattern (and same reasoning) as autoGenerateDialog.ts's
 * cachedCurve. Falls back to deps.level.shuffleCurve first when the level has
 * one recorded, since that's a more specific starting point than the
 * cross-level singleton.
 */
let cachedCurve: CurveState | null = null;

export function openAutoGenerateQueueDialog(deps: AutoGenerateQueueDeps): void {
  const close = () => overlay.remove();

  let mode: "fixed" | "curve" = "fixed";
  let fixedValue = 0;
  let curveState = deps.level.shuffleCurve
    ? parseCurve(deps.level.shuffleCurve, cachedCurve ?? defaultCurve(0, 5))
    : cachedCurve
      ? structuredClone(cachedCurve)
      : defaultCurve(0, 5);

  const modeBody = el("div", { class: "auto-generate-queue-mode-body" });

  const fixedInput = el("input", { type: "number", min: "0", value: "0" }) as HTMLInputElement;
  fixedInput.addEventListener("change", () => {
    fixedValue = Math.max(0, Number(fixedInput.value) || 0);
  });
  const fixedField = el("label", { class: "field" }, [
    "Shuffle range (limited-displacement shuffle within each lane after the row-major fill; 0 = none)",
    fixedInput,
  ]);

  const curveField = el("div", {}, [
    el("h3", {}, ["Shuffle Distance Curve (normalized position in lane → max displacement distance)"]),
    createCurveWithPresets(curveState, (next) => {
      curveState = next;
      cachedCurve = next;
    }),
  ]);

  let fixedBtn!: HTMLButtonElement;
  let curveBtn!: HTMLButtonElement;

  const setMode = (next: "fixed" | "curve") => {
    mode = next;
    fixedBtn.classList.toggle("active", mode === "fixed");
    curveBtn.classList.toggle("active", mode === "curve");
    modeBody.replaceChildren(mode === "fixed" ? fixedField : curveField);
  };

  fixedBtn = button("Fixed Value", () => setMode("fixed"), { class: "small-btn active" }) as HTMLButtonElement;
  curveBtn = button("Curve", () => setMode("curve"), { class: "small-btn" }) as HTMLButtonElement;
  modeBody.replaceChildren(fixedField);

  const panel = el("div", { class: "auto-generate-panel" }, [
    el("h3", {}, ["Shuffle Mode"]),
    el("div", { class: "toggle-group" }, [fixedBtn, curveBtn]),
    modeBody,
    el("div", { class: "auto-generate-actions" }, [
      button("Cancel", close),
      button(
        "Generate",
        () => {
          const spec: ShuffleRangeSpec =
            mode === "fixed" ? { kind: "fixed", value: fixedValue } : { kind: "curve", curve: curveState };
          if (mode === "curve") deps.level.shuffleCurve = serializeCurve(curveState);
          deps.onGenerate(spec);
          close();
        },
        { class: "primary" },
      ),
    ]),
  ]);

  const overlay = el("div", { class: "overlay-panel" }, [
    el("div", { class: "definitions-head" }, [
      el("h2", {}, ["Auto Generate Queue"]),
      button("✕ Close", close, { class: "primary" }),
    ]),
    panel,
  ]);
  overlay.addEventListener("click", (e) => {
    if (e.target === overlay) close();
  });
  document.body.append(overlay);
}
