// Customer Config — top tier of the Design page.
// Ordered arrival sequence of customers and the dish(es) each one orders.
// See docs/ToolDesign.md "Customer Config window".

import Sortable from "sortablejs";
import { CUSTOMER_STAFF } from "../../core/effects.ts";
import { parseCustomers, serializeCustomers } from "../../core/parser.ts";
import type { CustomerConfig, ElementDef, GlobalDefs, MapDef } from "../../core/types.ts";
import type { LevelData } from "../../data/mapLoader.ts";
import {
  addPickerGrid,
  closeContextMenu,
  importField,
  showContextContent,
  showContextMenu,
} from "../contextMenu.ts";
import type { MenuItem } from "../contextMenu.ts";
import { button, el } from "../dom.ts";
import { cookedIconEl, customerTypeIconEl } from "../icon.ts";
import { DEFAULT_MAX_DISH_SLOTS, parseDishCountSequence, serializeDishCountSequence } from "./autoGenerate.ts";
import { dishCountEditor, openAutoGenerateDialog } from "./autoGenerateDialog.ts";
import { changeClass, cidOf, tagAllNew, tagNew } from "./changeTracking.ts";
import type { ChangeStatus } from "./changeTracking.ts";
import { defaultCurve, openCurveDialog, parseCurve, serializeCurve } from "./curveEditor.ts";
import {
  DEFAULT_INGREDIENT_WEIGHT,
  openIngredientWeightsDialog,
  parseIngredientWeights,
  serializeIngredientWeights,
} from "./ingredientWeightEditor.ts";
import { Section } from "./section.ts";

export interface CustomerSectionDeps {
  map: MapDef;
  defs: GlobalDefs;
  level: LevelData;
  parse(): CustomerConfig[];
  onSaved(): void;
  /** Lets the queue section's Recipe Pieces counts follow order edits live. */
  onCommit?(): void;
  /** Fires after a successful Auto Generate — lets the caller chain into regenerating the queue to match. */
  onGenerated?(): void;
}

/**
 * Only Staff gets dedicated UI (no dish editor, a stack-amount field instead)
 * — every other type, known or not, renders the standard dish editor. New
 * types only need a row in general/customer-types.json (for the type-picker
 * menu and icon) and, if their behavior differs from a plain order-taking
 * customer, a registered handler in core/registry.ts; no UI change required
 * unless they need dedicated fields like Staff's amount.
 */
const isStaff = (c: CustomerConfig) => c.typeId === CUSTOMER_STAFF;

function typeDef(defs: GlobalDefs, typeId: number): ElementDef | undefined {
  return defs.customerTypes.find((t) => t.id === typeId);
}

/** Every cooked ingredient a customer's dishes call for, counted (a dish can repeat one). */
function cookedIdCounts(c: CustomerConfig): Map<number, number> {
  const counts = new Map<number, number>();
  for (const dish of c.dishes) {
    for (const id of dish.cookedIds) counts.set(id, (counts.get(id) ?? 0) + 1);
  }
  return counts;
}

/**
 * Matched by `_cid` (survives reordering). "removed-inside" covers losing a
 * whole dish or just one chip out of a dish — either way, the order asks for
 * less than it used to. Cooked ids aren't individually tagged (a dish can
 * repeat one), so this compares counts rather than identities.
 */
function customerStatus(
  customer: CustomerConfig,
  savedCustomers: CustomerConfig[],
): ChangeStatus | null {
  const cid = cidOf(customer);
  const saved = savedCustomers.find((c) => cidOf(c) === cid);
  if (!saved) return "added";

  if (saved.dishes.length > customer.dishes.length) return "removed-inside";
  const currentCounts = cookedIdCounts(customer);
  const savedCounts = cookedIdCounts(saved);
  for (const [id, count] of savedCounts) {
    if ((currentCounts.get(id) ?? 0) < count) return "removed-inside";
  }

  const unchanged =
    saved.typeId === customer.typeId &&
    saved.waitTime === customer.waitTime &&
    saved.weatherEff === customer.weatherEff &&
    (saved.staffAmount ?? 1) === (customer.staffAmount ?? 1) &&
    JSON.stringify(saved.dishes) === JSON.stringify(customer.dishes);
  return unchanged ? null : "modified";
}

export function createCustomerSection(deps: CustomerSectionDeps): Section<CustomerConfig[]> {
  const section: Section<CustomerConfig[]> = new Section<CustomerConfig[]>({
    title: "Customers",
    saveLabel: "Save Customers",
    initial: tagAllNew(deps.parse()),
    renderBody: (draft, body) => renderBody(section, deps, draft, body),
    onCommit: () => deps.onCommit?.(),
    save: (draft) => {
      deps.level.customerString = serializeCustomers(draft);
      deps.onSaved();
    },
    stringPreview: (draft) => serializeCustomers(draft),
    headerButtons: (sec) => [
      button("✨ Auto Generate", () => {
        openAutoGenerateDialog({
          map: deps.map,
          level: deps.level,
          currentCustomers: () => sec.draft,
          onGenerate: (generated) => {
            const tagged = tagAllNew(generated);
            const added = tagged.length;
            const removed = sec.draft.length;
            sec.draft.length = 0;
            sec.draft.push(...tagged);
            sec.commit("Auto-generate customers", added, removed);
            deps.onSaved(); // the dialog also wrote ingredientWeights/customerDishesSequence/complexityCurve onto deps.level
            deps.onGenerated?.();
          },
        });
      }, { title: "Generate a customer sequence from a dish-count list, ingredient weights, and a complexity curve" }),
    ],
    menuItems: (draft) => [
      {
        label: "Import from string…",
        expand: (close) =>
          importField("typeId;waitTime;weatherEff;dishes|...", (text) => {
            const parsed = tagAllNew(parseCustomers(text));
            const added = parsed.length;
            const removed = draft.length;
            draft.length = 0;
            draft.push(...parsed);
            section.commit("Import customers from string", added, removed);
            close();
          }),
      },
      {
        label: "Clear All",
        danger: true,
        separator: true,
        onSelect: () => {
          if (!confirm("Remove every customer from this level?")) return;
          const removed = draft.length;
          draft.length = 0;
          section.commit("Clear all customers", 0, removed);
        },
      },
    ],
  });
  section.render();
  return section;
}

function renderBody(
  section: Section<CustomerConfig[]>,
  deps: CustomerSectionDeps,
  draft: CustomerConfig[],
  body: HTMLElement,
): void {
  body.append(levelParamsBar(section, deps));

  const row = el("div", { class: "customer-cards", "data-scroll-key": "customer-cards" });

  const savedCustomers = section.savedState;
  draft.forEach((customer, index) => {
    row.append(customerCard(section, deps, draft, customer, index, savedCustomers));
  });

  const addCard = el("div", { class: "customer-card add-card" }, ["＋"]);
  addCard.title = "Append a customer";
  addCard.addEventListener("click", () => {
    draft.push(
      tagNew({ typeId: 0, waitTime: 0, weatherEff: 0, dishes: [{ cookedIds: [], effects: [] }] }),
    );
    section.commit("Add customer", 1);
  });
  row.append(addCard);

  Sortable.create(row, {
    animation: 150,
    draggable: ".customer-card:not(.add-card)",
    handle: ".customer-head",
    onEnd: (evt) => {
      if (evt.oldIndex === undefined || evt.newIndex === undefined) return;
      if (evt.oldIndex === evt.newIndex) return;
      const [moved] = draft.splice(evt.oldIndex, 1);
      draft.splice(Math.min(evt.newIndex, draft.length), 0, moved);
      section.commit("Reorder customers");
    },
  });

  body.append(row);
}

/**
 * Read-only record of the last Auto Generate run's inputs — Ingredient
 * Weights, Customer Dishes Sequence, Complexity Curve — each with an Edit
 * button that opens a standalone dialog for that one field. Editing here only
 * updates the stored string on deps.level; it doesn't touch the live
 * customer list (re-running Auto Generate is what applies it).
 */
function levelParamsBar(section: Section<CustomerConfig[]>, deps: CustomerSectionDeps): HTMLElement {
  const refresh = () => {
    deps.onSaved();
    section.render();
  };

  const weightsField = readOnlyField(
    "Ingredient Weights",
    deps.level.ingredientWeights ?? "",
    () => {
      const initial = deps.level.ingredientWeights
        ? parseIngredientWeights(deps.level.ingredientWeights)
        : new Map(deps.map.cookedIngredients.map((c) => [c.id, DEFAULT_INGREDIENT_WEIGHT]));
      openIngredientWeightsDialog(deps.map, initial, (weights) => {
        deps.level.ingredientWeights = serializeIngredientWeights(weights);
        refresh();
      });
    },
  );

  const dishSeqField = readOnlyField(
    "Customer Dishes Sequence",
    deps.level.customerDishesSequence ?? "",
    () => {
      const initial = deps.level.customerDishesSequence
        ? parseDishCountSequence(deps.level.customerDishesSequence)
        : [1, 1, 1];
      openDishCountDialog(initial, (counts) => {
        deps.level.customerDishesSequence = serializeDishCountSequence(counts);
        refresh();
      });
    },
  );

  const curveField = readOnlyField(
    "Complexity Curve",
    deps.level.complexityCurve ?? "",
    () => {
      const initial = deps.level.complexityCurve
        ? parseCurve(deps.level.complexityCurve, defaultCurve(1, DEFAULT_MAX_DISH_SLOTS))
        : defaultCurve(1, DEFAULT_MAX_DISH_SLOTS);
      openCurveDialog("Complexity Curve", initial, (curve) => {
        deps.level.complexityCurve = serializeCurve(curve);
        refresh();
      });
    },
  );

  return el("div", { class: "level-params-bar" }, [weightsField, dishSeqField, curveField]);
}

function readOnlyField(label: string, value: string, onEdit: () => void): HTMLElement {
  const input = el("input", { type: "text", value, readonly: "true" }) as HTMLInputElement;
  return el("label", { class: "field level-param-field" }, [
    label,
    el("div", { class: "level-param-row" }, [input, button("Edit", onEdit, { class: "small-btn" })]),
  ]);
}

/** Standalone "edit just the dish-count sequence" popup — the same list editor Auto Generate uses. */
function openDishCountDialog(initial: number[], onApply: (counts: number[]) => void): void {
  const close = () => overlay.remove();
  let counts = [...initial];

  const panel = el("div", { class: "auto-generate-panel" }, [
    dishCountEditor(initial, (next) => (counts = next)),
    el("div", { class: "auto-generate-actions" }, [
      button("Cancel", close),
      button("Apply", () => { onApply(counts); close(); }, { class: "primary" }),
    ]),
  ]);

  const overlay = el("div", { class: "overlay-panel" }, [
    el("div", { class: "definitions-head" }, [
      el("h2", {}, ["Customer Dishes Sequence"]),
      button("✕ Close", close, { class: "primary" }),
    ]),
    panel,
  ]);
  overlay.addEventListener("click", (e) => {
    if (e.target === overlay) close();
  });
  document.body.append(overlay);
}

function customerCard(
  section: Section<CustomerConfig[]>,
  deps: CustomerSectionDeps,
  draft: CustomerConfig[],
  customer: CustomerConfig,
  index: number,
  savedCustomers: CustomerConfig[],
): HTMLElement {
  const staff = isStaff(customer);
  const status = customerStatus(customer, savedCustomers);
  // A subtle tint so a wait-timed or weather-affected order stands out from
  // a plain one at a glance, without competing with the change-tracking
  // border colors (added/modified/removed-inside).
  const timed = customer.weatherEff !== 0 || customer.waitTime > 0;
  const card = el("div", {
    class: `customer-card${staff ? " staff" : ""}${timed ? " timed" : ""} ${changeClass(status)}`,
  });

  const waitInput = el("input", {
    type: "number",
    value: String(customer.waitTime),
    title: "Patience timer in seconds (0 = no limit)",
  }) as HTMLInputElement;
  waitInput.addEventListener("change", () => {
    customer.waitTime = Number(waitInput.value) || 0;
    section.commit("Set wait time");
  });

  const weatherToggle = button(
    customer.weatherEff ? "🌧" : "☁",
    () => {
      customer.weatherEff = customer.weatherEff ? 0 : 1;
      section.commit("Toggle weather effect");
    },
    {
      class: `weather-toggle${customer.weatherEff ? " on" : ""}`,
      title: "Weather-affected: bad weather halves this customer's patience",
    },
  );

  const def = typeDef(deps.defs, customer.typeId);
  const typeMark = def && def.id !== 0 ? ` ${def.icon || def.name}` : "";
  const head = el("div", { class: "customer-head" }, [
    el("span", { class: "cust-index" }, [`#${index + 1}${typeMark}`]),
    el("span", { class: "wait-badge" }, [
      customer.waitTime === 0 ? "∞" : "", waitInput,
    ]),
    weatherToggle,
  ]);
  head.addEventListener("contextmenu", (e) =>
    showContextMenu(e, cardMenu(section, deps, draft, customer, index), {
      title: `Customer #${index + 1}`,
    }),
  );
  card.append(head);

  if (staff) {
    const amountInput = el("input", {
      type: "number",
      min: "1",
      value: String(customer.staffAmount ?? 1),
      title: "How many dirty stacks this staff clears on arrival (even a partial stack counts)",
    }) as HTMLInputElement;
    amountInput.addEventListener("change", () => {
      customer.staffAmount = Math.max(1, Number(amountInput.value) || 1);
      section.commit("Set staff stack amount");
    });
    card.append(
      el("div", { class: "staff-note" }, [
        "Staff — clears ",
        amountInput,
        " dirty stack(s)",
      ]),
    );
  } else {
    customer.dishes.forEach((dish, di) => {
      const dishRow = el("div", { class: "dish-row" }, [
        el("span", { class: "dish-label" }, [`D${di + 1}`]),
      ]);
      const chipsRow = el("div", { class: "dish-chips" });

      dish.cookedIds.forEach((cookedId, ci) => {
        const chip = el("span", { class: "chip icon-chip dish-chip" }, [cookedIconEl(cookedId, 64)]);
        chip.title = deps.map.cookedIngredients.find((c) => c.id === cookedId)?.name ?? "";
        chip.addEventListener("contextmenu", (e) => {
          e.preventDefault();
          e.stopPropagation();
          // This slot's own current ingredient doesn't count against its own
          // Limit — it's being replaced, not added alongside itself.
          const counts = new Map<number, number>();
          for (const id of dish.cookedIds) counts.set(id, (counts.get(id) ?? 0) + 1);
          counts.set(cookedId, Math.max(0, (counts.get(cookedId) ?? 1) - 1));

          const wrap = el("div", { class: "ctx-swap" });
          wrap.append(
            addPickerGrid(
              deps.map.cookedIngredients.map((c) => ({
                id: c.id,
                label: c.name,
                icon: cookedIconEl(c.id, 64),
                limit: c.limit,
              })),
              counts,
              (id) => {
                dish.cookedIds[ci] = id;
                section.commit("Swap dish ingredient");
                closeContextMenu();
              },
            ),
            button(
              "Remove",
              () => {
                dish.cookedIds.splice(ci, 1);
                section.commit("Remove ingredient from dish", 0, 1);
                closeContextMenu();
              },
              { class: "danger ctx-swap-remove" },
            ),
          );
          showContextContent(e, wrap, { title: `Swap: ${chip.title}` });
        });
        chipsRow.append(chip);
      });

      // The picker only ever adds (right-click an existing chip to swap or
      // remove instead). It stays open across clicks instead of closing
      // after each pick — the menu's own click-outside/Escape handling is
      // what closes it. Each ingredient stops being pickable once its
      // configured Limit copies are already in this dish (absent/0 = no limit).
      const addChip = button(
        "＋",
        (e) => {
          const counts = new Map<number, number>();
          for (const id of dish.cookedIds) counts.set(id, (counts.get(id) ?? 0) + 1);
          showContextContent(
            e,
            addPickerGrid(
              deps.map.cookedIngredients.map((c) => ({
                id: c.id,
                label: c.name,
                icon: cookedIconEl(c.id, 64),
                limit: c.limit,
              })),
              counts,
              (id) => {
                dish.cookedIds.push(id);
                section.commit("Add ingredient to dish", 1, 0);
              },
            ),
            { title: `Dish ${di + 1}` },
          );
        },
        { class: "chip add-chip" },
      );
      chipsRow.append(addChip);

      // Chips reorder within their dish by drag (addChip stays put — it's
      // excluded from `draggable`, so it's never a valid drop target itself,
      // only the fixed trailing element).
      Sortable.create(chipsRow, {
        animation: 150,
        draggable: ".dish-chip",
        onEnd: (evt) => {
          if (evt.oldIndex === undefined || evt.newIndex === undefined) return;
          if (evt.oldIndex === evt.newIndex) return;
          const [moved] = dish.cookedIds.splice(evt.oldIndex, 1);
          dish.cookedIds.splice(Math.min(evt.newIndex, dish.cookedIds.length), 0, moved);
          section.commit("Reorder dish ingredients");
        },
      });

      dishRow.append(chipsRow);

      // Dish effects come from a separate, not-yet-defined table (distinct
      // from ingredient statuses) — nothing to show or offer here for now.

      dishRow.addEventListener("contextmenu", (e) =>
        showContextMenu(e, dishMenu(section, customer, di), { title: `Dish ${di + 1}` }),
      );
      card.append(dishRow);
    });

    card.append(
      button(
        "+ Dish",
        () => {
          // Dishes aren't individually tagged (a dish can repeat a cooked id,
          // so identity isn't meaningful the way it is for a whole customer) —
          // customerStatus compares dish content directly instead.
          customer.dishes.push({ cookedIds: [], effects: [] });
          section.commit("Add dish", 1);
        },
        { class: "small-btn add-dish" },
      ),
    );
  }

  return card;
}

function cardMenu(
  section: Section<CustomerConfig[]>,
  deps: CustomerSectionDeps,
  draft: CustomerConfig[],
  customer: CustomerConfig,
  index: number,
): MenuItem[] {
  const blank = (): CustomerConfig =>
    tagNew({
      typeId: 0,
      waitTime: 0,
      weatherEff: 0,
      dishes: [{ cookedIds: [], effects: [] }],
    });

  // One entry per row in the customer-types table — adding a type there is
  // all it takes for it to show up here, no code change needed.
  const typeItems: MenuItem[] = deps.defs.customerTypes.map((def, i) => ({
    label: `Type: ${def.name}`,
    icon: customerTypeIconEl(def.id, 48),
    active: customer.typeId === def.id,
    separator: i === 0,
    onSelect: () => {
      customer.typeId = def.id;
      // Staff orders nothing; anything else needs at least one dish to edit.
      if (def.id === CUSTOMER_STAFF) customer.dishes = [];
      else if (customer.dishes.length === 0) customer.dishes = [{ cookedIds: [], effects: [] }];
      section.commit(`Set type: ${def.name}`);
    },
  }));

  return [
    {
      label: "Insert Before",
      onSelect: () => {
        draft.splice(index, 0, blank());
        section.commit("Insert customer before", 1);
      },
    },
    {
      label: "Insert After",
      onSelect: () => {
        draft.splice(index + 1, 0, blank());
        section.commit("Insert customer after", 1);
      },
    },
    {
      label: "Duplicate",
      onSelect: () => {
        // A fresh identity — otherwise the clone would inherit the original's
        // _cid (structuredClone copies it) and get matched against it as the
        // "same" customer instead of showing as newly added.
        draft.splice(index + 1, 0, tagNew(structuredClone(customer)));
        section.commit("Duplicate customer", 1);
      },
    },
    ...typeItems,
    {
      label: "Remove",
      danger: true,
      separator: true,
      onSelect: () => {
        draft.splice(index, 1);
        section.commit("Remove customer", 0, 1);
      },
    },
  ];
}

/**
 * Dish statuses live in a separate table from ingredient statuses, not yet
 * defined — so this menu deliberately offers nothing for them (per the ask,
 * "leave it blank and not show in right-click menu") until that table exists.
 */
function dishMenu(
  section: Section<CustomerConfig[]>,
  customer: CustomerConfig,
  dishIndex: number,
): MenuItem[] {
  const items: MenuItem[] = [];

  items.push({
    label: "Remove Dish",
    danger: true,
    onSelect: () => {
      customer.dishes.splice(dishIndex, 1);
      section.commit("Remove dish", 0, 1);
    },
  });
  return items;
}
