// The small modals Level Path owns: a level-range prompt for Batch Generate, a
// dish-sequence editor, and the new-map prompt.
//
// They reuse the existing `.overlay-panel` / `.auto-generate-panel` chrome
// rather than inventing a third dialog look, so every popup in the tool still
// opens, closes and reads the same way.

import { button, el } from "../dom.ts";
import { dishCountEditor } from "../design/autoGenerateDialog.ts";

/** Shell shared by every dialog here: title bar, click-outside to close, Cancel/confirm footer. */
function openDialog(
  title: string,
  body: (Node | string)[],
  confirmLabel: string,
  onConfirm: () => boolean | void,
): void {
  const close = () => overlay.remove();

  const panel = el("div", { class: "auto-generate-panel" }, [
    ...body,
    el("div", { class: "auto-generate-actions" }, [
      button("Cancel", close),
      button(
        confirmLabel,
        () => {
          // A confirm handler returning false means "not valid yet" — keep the
          // dialog open so the designer can see and fix what they typed.
          if (onConfirm() === false) return;
          close();
        },
        { class: "primary" },
      ),
    ]),
  ]);

  const overlay = el("div", { class: "overlay-panel" }, [
    el("div", { class: "definitions-head" }, [
      el("h2", {}, [title]),
      button("✕ Close", close, { class: "primary" }),
    ]),
    panel,
  ]);
  overlay.addEventListener("click", (e) => {
    if (e.target === overlay) close();
  });
  document.body.append(overlay);
}

function numberField(label: string, value: number, min: number): {
  field: HTMLElement;
  input: HTMLInputElement;
} {
  const input = el("input", { type: "number", min: String(min), value: String(value) }) as HTMLInputElement;
  return { field: el("label", { class: "field" }, [label, input]), input };
}

export interface BatchRange {
  from: number;
  to: number;
  /** Roll fresh weights/curves instead of reusing what each level already records. */
  reroll: boolean;
}

/**
 * "Generate levels X to Y". The range is in LEVEL POSITION (the #n the table
 * shows), not level id — that is the number the designer is looking at, and
 * ids are not guaranteed contiguous.
 */
export function openBatchGenerateDialog(
  mapTitle: string,
  levelCount: number,
  onRun: (range: BatchRange) => void,
): void {
  const from = numberField("From level #", 1, 1);
  const to = numberField("To level #", Math.max(1, levelCount), 1);
  const reroll = el("input", { type: "checkbox" }) as HTMLInputElement;

  openDialog(
    `Batch generate — ${mapTitle}`,
    [
      el("p", { class: "muted" }, [
        `This map has ${levelCount} level(s). A range reaching past the end CREATES the missing levels; ` +
          "levels inside the range are overwritten.",
      ]),
      el("div", { class: "lp-dialog-row" }, [from.field, to.field]),
      el("label", { class: "field" }, [
        el("span", {}, [reroll, " Reroll generator config"]),
      ]),
      el("p", { class: "muted" }, [
        "Off: each level reuses the weights, dish sequence and curves it already records, and only rebuilds " +
          "its strings. On: everything except a pinned seed is rolled fresh.",
      ]),
    ],
    "Generate",
    () => {
      const start = Math.max(1, Math.round(Number(from.input.value) || 1));
      const end = Math.max(start, Math.round(Number(to.input.value) || start));
      onRun({ from: start, to: end, reroll: reroll.checked });
    },
  );
}

/** The dish-count-per-customer sequence, using the same editor the Auto Generate dialog uses. */
export function openDishSequenceDialog(
  levelName: string,
  initial: number[],
  onApply: (counts: number[]) => void,
): void {
  let counts = [...initial];
  openDialog(
    `Customer dish sequence — ${levelName}`,
    [
      el("p", { class: "muted" }, [
        "One entry per customer, in arrival order. -1 = Staff, 0 = Auto (the complexity curve picks).",
      ]),
      dishCountEditor(initial, (next) => (counts = next)),
    ],
    "Apply",
    () => onApply(counts),
  );
}

/** "+ Map": a name and how many levels to start it with. */
export function openNewMapDialog(defaultLevels: number, onCreate: (name: string, levels: number) => void): void {
  const nameInput = el("input", { type: "text", placeholder: "Map name" }) as HTMLInputElement;
  const levels = numberField("Levels to create", defaultLevels, 1);

  openDialog(
    "New map",
    [
      el("label", { class: "field" }, ["Name", nameInput]),
      levels.field,
      el("p", { class: "muted" }, [
        "Creates an empty map process graph. The levels start blank — generate them once the graph has nodes.",
      ]),
    ],
    "Create",
    () => {
      const name = nameInput.value.trim();
      if (!name) {
        nameInput.focus();
        return false;
      }
      onCreate(name, Math.max(1, Math.round(Number(levels.input.value) || 1)));
      return true;
    },
  );
}
