import { parseNodeCustomers } from "../../core/nodeParser.ts";
import { parseQueues } from "../../core/parser.ts";
import type { GraphIndex } from "../../core/nodeIndex.ts";
import type { IdIndex } from "../../data/nodeIdTable.ts";
import type { LevelData } from "../../data/mapLoader.ts";
import type { ProjectedMap } from "../../data/nodeGraphToMapDef.ts";
import {
  applyWorkspaceEnvelopeToLevel,
  refreshGeneratorWorkspaceData,
  type GeneratorWorkspaceEnvelopeV2,
} from "../../data/generatorPersistence/index.ts";
import type { NodeCustomerConfig } from "../../core/nodeParser.ts";
import type { EstimateScenario } from "../design/estimateScenario.ts";
import {
  DEFAULT_DISH_COUNT_SEQUENCE,
  DEFAULT_MAX_DISH_SLOTS,
  parseDishCountSequence,
  serializeDishCountSequence,
} from "../design/autoGenerate.ts";
import { dishCountEditor } from "../design/autoGenerateDialog.ts";
import { createCurveWithPresets, defaultCurve, parseCurve, serializeCurve, type CurveState } from "../design/curveEditor.ts";
import type { GenerateLevelResult } from "../levelpath/generateLevel.ts";
import { loadConfig } from "../levelpath/config.ts";
import type { BagFillMode } from "../nodedesign/nodeQueueGenerate.ts";
import { button, el } from "../dom.ts";
import { createSharedProfileEditor } from "./sharedProfileEditor.ts";
import { startBackgroundGeneration, type BackgroundGenerationTask } from "./backgroundGeneration.ts";
import { createResizableGeneratorColumns, type GeneratorColumnWidths } from "./resizableColumns.ts";
import { captureModalScrollState, restoreModalScrollState } from "./modalScrollState.ts";

export interface CustomerFirstWorkspaceOptions {
  mapId: string;
  level: LevelData;
  ix: GraphIndex;
  ids: IdIndex;
  projected: ProjectedMap;
  envelope: GeneratorWorkspaceEnvelopeV2;
  currentCustomers(): NodeCustomerConfig[];
  scenario?: EstimateScenario;
  onEnvelopeChanged(envelope: GeneratorWorkspaceEnvelopeV2): void;
  onGenerated(result: GenerateLevelResult): void;
  onSwitchToQueue(): void;
  onClosed?(): void;
}

function basisOf(level: LevelData, ix: GraphIndex) {
  const queueSlots = (() => { try { return parseQueues(level.queueString).reduce((n, lane) => n + lane.length, 0); } catch { return 0; } })();
  const orderingCustomers = (() => { try { return parseNodeCustomers(level.customerString).filter((c) => c.typeId !== 1).length; } catch { return 0; } })();
  return {
    gridCells: ix.doc.map.gridWidth * ix.doc.map.gridHeight,
    queueSlots,
    orderingCustomers,
  };
}

export function openCustomerFirstWorkspace(options: CustomerFirstWorkspaceOptions): void {
  let envelope = structuredClone(options.envelope);
  let preview: LevelData | undefined;
  let previewResult: GenerateLevelResult | undefined;
  let page: "setup" | "review" = "setup";
  let editorMode: "visual" | "json" = "visual";
  let busy = false;
  let generationTask: BackgroundGenerationTask<{ level: LevelData; result: GenerateLevelResult }> | undefined;
  let autosaveTimer: ReturnType<typeof setTimeout> | undefined;
  const foldoutState = new Map<string, boolean>();
  const columnWidths: GeneratorColumnWidths = {};
  let lastRenderedPage: "setup" | "review" | undefined;

  const existing = options.currentCustomers();
  let dishCounts = envelope.customerFirst.customerDishesSequence
    ? parseDishCountSequence(envelope.customerFirst.customerDishesSequence)
    : existing.length ? existing.map((customer) => customer.typeId === 1 ? -1 : 0) : [...DEFAULT_DISH_COUNT_SEQUENCE];
  let curve: CurveState = envelope.customerFirst.complexityCurve
    ? parseCurve(envelope.customerFirst.complexityCurve, defaultCurve(1, DEFAULT_MAX_DISH_SLOTS))
    : defaultCurve(1, DEFAULT_MAX_DISH_SLOTS);
  let shuffle: CurveState = envelope.customerFirst.shuffleCurve
    ? parseCurve(envelope.customerFirst.shuffleCurve, defaultCurve(0, 5))
    : defaultCurve(0, 5);
  let bagFill: BagFillMode = envelope.customerFirst.bagFill ?? "random";

  const overlay = el("div", { class: "overlay-panel queue-first-overlay" });
  const shell = el("div", { class: "queue-first-workspace unified-generator-workspace" });
  overlay.append(shell);
  const close = (): void => {
    generationTask?.cancel();
    if (autosaveTimer) clearTimeout(autosaveTimer);
    saveEnvelope();
    overlay.remove();
    options.onClosed?.();
  };

  function captureControls(): void {
    envelope.customerFirst.customerDishesSequence = serializeDishCountSequence(dishCounts);
    envelope.customerFirst.complexityCurve = serializeCurve(curve);
    envelope.customerFirst.shuffleCurve = serializeCurve(shuffle);
    envelope.customerFirst.bagFill = bagFill;
    envelope.activeStrategy = "customer-first";
    envelope = refreshGeneratorWorkspaceData(envelope);
  }

  function saveEnvelope(): void {
    captureControls();
    envelope = applyWorkspaceEnvelopeToLevel(options.level, envelope, options.ix, options.ids, options.projected);
    options.onEnvelopeChanged(envelope);
  }

  function scheduleAutosave(): void {
    if (autosaveTimer) clearTimeout(autosaveTimer);
    autosaveTimer = setTimeout(() => {
      autosaveTimer = undefined;
      saveEnvelope();
      renderStatus("Draft saved locally.", "ok");
    }, 250);
  }

  const statusHost = el("div", { class: "generator-inline-status", role: "status" });
  function renderStatus(message: string, kind: "ok" | "warning" | "error" = "ok", progress?: number): void {
    statusHost.className = `generator-inline-status ${kind}`;
    statusHost.replaceChildren(
      ...(progress === undefined ? [] : [el("span", { class: "generator-progress-fill", "aria-hidden": "true" })]),
      el("span", { class: "generator-progress-label" }, [message]),
    );
    if (progress === undefined) {
      statusHost.setAttribute("role", kind === "error" ? "alert" : "status");
      statusHost.removeAttribute("aria-valuemin");
      statusHost.removeAttribute("aria-valuemax");
      statusHost.removeAttribute("aria-valuenow");
      statusHost.style.removeProperty("--generator-progress");
    } else {
      const value = Math.max(0, Math.min(100, progress));
      statusHost.classList.add("running");
      statusHost.style.setProperty("--generator-progress", `${value}%`);
      statusHost.setAttribute("role", "progressbar");
      statusHost.setAttribute("aria-valuemin", "0");
      statusHost.setAttribute("aria-valuemax", "100");
      statusHost.setAttribute("aria-valuenow", String(Math.round(value)));
    }
  }

  function section(title: string, body: (Node | string)[]): HTMLElement {
    const details = el("details", { class: "generate-section" }, [
      el("summary", { title: `Expand ${title} configuration` }, [title]),
      el("div", { class: "generate-section-body" }, body),
    ]);
    details.open = foldoutState.get(title) ?? false;
    details.addEventListener("toggle", () => foldoutState.set(title, details.open));
    return details;
  }

  function setupPanel(): HTMLElement {
    const shared = createSharedProfileEditor({
      profile: envelope.shared,
      ix: options.ix,
      ids: options.ids,
      projected: options.projected,
      basis: basisOf(preview ?? options.level, options.ix),
      impactText: "Dish-type and ingredient weights are shared by both strategies. Here they shape dishes first; queue supply is derived from those orders.",
      foldoutState,
      statePrefix: "customer-shared:",
      mode: editorMode,
      showModeToggle: false,
      onChange: (next) => {
        envelope.shared = next;
        scheduleAutosave();
      },
    });
    if (editorMode === "json") {
      const json = el("textarea", { class: "qf-vector-json", rows: "24", "aria-label": "Customer-first configuration JSON" }) as HTMLTextAreaElement;
      const error = el("p", { class: "inline-error", role: "alert" });
      const syncJson = (): void => {
        json.value = JSON.stringify({
          customerDishesSequence: dishCounts,
          complexityCurve: curve,
          shuffleCurve: shuffle,
          bagFill,
        }, null, 2);
      };
      json.addEventListener("input", () => {
        try {
          const parsed = JSON.parse(json.value) as {
            customerDishesSequence: number[];
            complexityCurve: CurveState;
            shuffleCurve: CurveState;
            bagFill: BagFillMode;
          };
          dishCounts = parsed.customerDishesSequence;
          curve = parsed.complexityCurve;
          shuffle = parsed.shuffleCurve;
          bagFill = parsed.bagFill;
          error.textContent = "";
          error.hidden = true;
          json.classList.remove("invalid");
          scheduleAutosave();
        } catch (cause) {
          error.textContent = `Invalid customer-first JSON: ${cause instanceof Error ? cause.message : String(cause)}`;
          error.hidden = false;
          json.classList.add("invalid");
        }
      });
      syncJson();
      return el("div", { class: "generator-setup-scroll" }, [
        section("Shared setup", [shared]),
        section("Customer-first settings", [
          el("p", { class: "muted qf-editor-help" }, ["Advanced editor for customer sequence, complexity, shuffle, and bag-fill configuration."]),
          json,
          error,
        ]),
      ]);
    }
    const bag = el("select") as HTMLSelectElement;
    for (const value of ["min", "random", "max"] as const) {
      const option = el("option", { value }, [value === "random" ? "Random (default)" : value[0].toUpperCase() + value.slice(1)]);
      option.selected = value === bagFill;
      bag.append(option);
    }
    bag.addEventListener("change", () => { bagFill = bag.value as BagFillMode; scheduleAutosave(); });
    return el("div", { class: "generator-setup-scroll" }, [
      section("Shared setup", [shared]),
      section("Customers", [dishCountEditor(dishCounts, (next) => { dishCounts = next; scheduleAutosave(); }, existing.map((c) => c.dishes.length))]),
      section("Complexity curve", [createCurveWithPresets(curve, (next) => { curve = next; scheduleAutosave(); })]),
      section("Queue policy", [
        el("label", { class: "field" }, ["Bag fill inside amount range", bag]),
        el("h4", {}, ["Shuffle distance"]),
        createCurveWithPresets(shuffle, (next) => { shuffle = next; scheduleAutosave(); }),
      ]),
    ]);
  }

  function previewPanel(): HTMLElement {
    const source = preview ?? options.level;
    const customers = (() => { try { return parseNodeCustomers(source.customerString); } catch { return []; } })();
    const queues = (() => { try { return parseQueues(source.queueString); } catch { return []; } })();
    const slots = queues.reduce((sum, lane) => sum + lane.length, 0);
    return el("div", { class: "generator-preview" }, [
      el("h3", {}, [preview ? "Generated preview" : "Current level"]),
      el("div", { class: "generator-metric-grid" }, [
        el("div", { class: "generator-metric" }, [el("strong", {}, [String(customers.length)]), el("span", {}, ["Customers"])]),
        el("div", { class: "generator-metric" }, [el("strong", {}, [String(customers.reduce((n, c) => n + c.dishes.length, 0))]), el("span", {}, ["Dishes"])]),
        el("div", { class: "generator-metric" }, [el("strong", {}, [String(queues.length)]), el("span", {}, ["Queue lanes"])]),
        el("div", { class: "generator-metric" }, [el("strong", {}, [String(slots)]), el("span", {}, ["Queue slots"])]),
      ]),
      el("p", { class: "muted" }, [preview
        ? "Preview is isolated from the playable level until Commit to Level."
        : "Generate a preview to compare a complete Customers → Queue result before replacing the level."]),
    ]);
  }

  function diagnosticsPanel(): HTMLElement {
    const messages = previewResult
      ? [...previewResult.errors.map((text) => ({ text, kind: "error" })), ...previewResult.warnings.map((text) => ({ text, kind: "warning" }))]
      : envelope.migrationWarnings.map((text) => ({ text, kind: "warning" }));
    return el("aside", { class: "qf-artifact generator-diagnostics" }, [
      el("h3", {}, ["Validation & diagnostics"]),
      el("p", {}, [`Strategy: Customers → Queue`]),
      el("p", {}, [`Workspace: ${envelope.contentHash.slice(0, 10)}`]),
      ...(messages.length ? [el("ul", { class: "generator-issues" }, messages.map((item) => el("li", { class: item.kind }, [item.text])))]
        : [el("p", { class: "generator-empty-state" }, [previewResult?.ok ? "Preview passed generation checks." : "No issues yet."])]),
    ]);
  }

  async function generatePreview(): Promise<void> {
    if (busy) return;
    saveEnvelope();
    busy = true;
    renderStatus("0% · Preparing background generation…", "ok", 0);
    render();
    const candidate = structuredClone(options.level);
    applyWorkspaceEnvelopeToLevel(candidate, envelope, options.ix, options.ids, options.projected);
    generationTask = startBackgroundGeneration<{ level: LevelData; result: GenerateLevelResult }>({
      kind: "customer-first",
      level: candidate,
      doc: options.ix.doc,
      ...(options.scenario ? { scenario: options.scenario } : {}),
      bounds: loadConfig().bounds,
      obstacleCoverage: {
        ...envelope.shared.obstacles,
        grid: { blocked: 0, orderLock: 0, ingredientLock: 0, lockAndKey: 0 },
      },
      preserveGridData: true,
    }, (percentage, description) => {
      renderStatus(`${Math.round(percentage)}% · ${description}`, "ok", percentage);
    });
    try {
      const generated = await generationTask.promise;
      const result = generated.result;
      previewResult = result;
      preview = result.ok ? generated.level : undefined;
      page = result.ok ? "review" : "setup";
      renderStatus(result.ok ? "Preview ready. Review it before committing." : "Preview failed. Review the diagnostics.", result.ok ? "ok" : "error");
    } catch (error) {
      if ((error as DOMException).name !== "AbortError") {
        preview = undefined;
        previewResult = undefined;
        renderStatus(`Background generation failed: ${error instanceof Error ? error.message : String(error)}`, "error");
      }
    } finally {
      generationTask = undefined;
      busy = false;
      render();
    }
  }

  function commit(): void {
    if (!preview || !previewResult?.ok) return;
    for (const key of ["customerString", "queueString", "gridString", "ingredientWeights", "customerDishesSequence", "complexityCurve", "shuffleCurve", "bagFill", "randomSeed", "obstacleData"] as const) {
      (options.level as unknown as Record<string, unknown>)[key] = preview[key];
    }
    saveEnvelope();
    options.onGenerated(previewResult);
    renderStatus("Preview committed to the playable level.", "ok");
    preview = undefined;
    previewResult = undefined;
    page = "setup";
    render();
  }

  function render(): void {
    const scrollPositions = lastRenderedPage === page
      ? captureModalScrollState(shell)
      : [];
    const customerButton = button("Customers → Queue", () => {}, { class: "selected", "aria-current": "page" });
    const queueButton = button("Queue → Pickup → Customers", () => {
      saveEnvelope();
      overlay.remove();
      options.onSwitchToQueue();
    });
    const primary = page === "review"
      ? button("Commit to Level", commit, { class: "primary" })
      : button(busy ? "Generating…" : "Generate Preview", generatePreview, { class: "primary" });
    primary.disabled = busy;
    const switchEditorMode = (next: "visual" | "json"): void => {
      if (next === editorMode) return;
      if (editorMode === "json") {
        const invalid = shell.querySelector<HTMLTextAreaElement>(".qf-vector-json.invalid");
        if (invalid) {
          invalid.focus();
          renderStatus("Fix invalid JSON before returning to Visual mode.", "error");
          return;
        }
      }
      editorMode = next;
      render();
    };
    const visualButton = button("Visual", () => switchEditorMode("visual"), { class: editorMode === "visual" ? "selected" : "" });
    const jsonButton = button("JSON", () => switchEditorMode("json"), { class: editorMode === "json" ? "selected" : "" });
    const configPanel = el("section", { class: "qf-vector" }, [page === "setup" ? setupPanel() : el("div", {}, [el("h3", {}, ["Preview settings locked"]), el("p", { class: "muted" }, ["Return to Setup to revise the shared profile or customer-first configuration."])])]);
    const contentPanel = el("section", { class: "qf-canvas" }, [previewPanel()]);
    const issuesPanel = diagnosticsPanel();
    const main = createResizableGeneratorColumns({
      config: configPanel,
      content: contentPanel,
      issues: issuesPanel,
      widths: columnWidths,
    });
    shell.replaceChildren(
      el("header", { class: "qf-head unified-generator-head" }, [
        el("div", {}, [el("h2", {}, ["Level Generator"]), el("small", {}, [`${options.mapId} · Level ${options.level.id}`])]),
        el("div", { class: "generator-strategy-switch", role: "tablist", "aria-label": "Generation strategy" }, [customerButton, queueButton]),
        el("div", { class: "generator-head-status" }, [el("span", { class: "status-chip" }, ["Local draft"]), button("✕ Close", close)]),
      ]),
      el("nav", { class: "qf-rail generator-step-rail" }, [
        button("1 Setup", () => { page = "setup"; render(); }, { class: page === "setup" ? "selected" : "" }),
        button(`2 Review${preview ? " ✓" : ""}`, () => { if (preview) { page = "review"; render(); } }, { class: page === "review" ? "selected" : "" }),
        el("span", { class: "spacer" }),
        el("div", { class: "qf-editor-tabs generator-global-editor-mode", role: "tablist", "aria-label": "Configuration editor mode" }, [visualButton, jsonButton]),
      ]),
      statusHost,
      main,
      el("footer", { class: "qf-actions unified-generator-actions" }, [
        ...(page === "review" ? [button("← Back to Setup", () => { page = "setup"; render(); })] : []),
        el("span", { class: "spacer" }),
        primary,
      ]),
    );
    restoreModalScrollState(shell, scrollPositions);
    lastRenderedPage = page;
  }

  overlay.addEventListener("click", (event) => { if (event.target === overlay) close(); });
  document.body.append(overlay);
  render();
}
