import type { AgentLevelEntry, AgentLevelProfile } from "../../data/agentLevels.ts";
import { loadAgentLevels } from "../../data/agentLevels.ts";
import { button, el } from "../dom.ts";

export class AgentDesignView {
  private loadRevision = 0;

  constructor(
    private readonly root: HTMLElement,
    private readonly onPlay: (profile: AgentLevelProfile, level: AgentLevelEntry) => void,
  ) {
    void this.render();
  }

  destroy(): void {
    this.loadRevision++;
  }

  private async render(): Promise<void> {
    const revision = ++this.loadRevision;
    const content = el("div", { class: "agent-design-content" }, [
      el("p", { class: "muted" }, ["Loading committed agent level profiles…"]),
    ]);
    this.root.replaceChildren(el("section", { class: "agent-design-page" }, [
      el("div", { class: "agent-design-heading" }, [
        el("div", {}, [
          el("h2", {}, ["Agent Design"]),
          el("p", { class: "muted" }, [
            "Playtest levels generated by local agent sessions and published with this site.",
          ]),
        ]),
        button("↻ Refresh", () => void this.render()),
      ]),
      content,
    ]));

    try {
      const loaded = await loadAgentLevels();
      if (revision !== this.loadRevision) return;
      content.replaceChildren();
      if (loaded.warnings.length) {
        content.append(el("div", { class: "warnings" }, [
          el("strong", {}, ["Some agent profiles could not be loaded"]),
          ...loaded.warnings.map((warning) => el("p", {}, [warning])),
        ]));
      }
      if (!loaded.profiles.length) {
        content.append(el("div", { class: "agent-empty" }, [
          el("h3", {}, ["No generated levels are published yet"]),
          el("p", {}, [
            "Finalize a local MCP level session, then run the Agent Design publish command. Commit and push the generated profile files to deploy them here.",
          ]),
        ]));
        return;
      }
      loaded.profiles.forEach((profile, index) => content.append(this.profile(profile, index === 0)));
    } catch (error) {
      if (revision !== this.loadRevision) return;
      content.replaceChildren(el("div", { class: "warnings" }, [
        el("strong", {}, ["Agent Design data could not be loaded"]),
        el("p", {}, [(error as Error).message]),
        button("Try again", () => void this.render(), { class: "primary" }),
      ]));
    }
  }

  private profile(profile: AgentLevelProfile, open: boolean): HTMLElement {
    const details = el("details", { class: "agent-profile" });
    details.open = open;
    details.append(
      el("summary", {}, [
        el("span", { class: "agent-profile-name" }, [profile.name]),
        el("span", { class: "agent-profile-count" }, [
          `${profile.levels.length} level${profile.levels.length === 1 ? "" : "s"}`,
        ]),
      ]),
      el("div", { class: "agent-profile-body" }, [
        ...(profile.description ? [el("p", { class: "muted" }, [profile.description])] : []),
        ...(profile.levels.length
          ? profile.levels.map((level) => this.level(profile, level))
          : [el("p", { class: "agent-empty muted" }, ["This profile does not contain a level yet."])]),
      ]),
    );
    return details;
  }

  private level(profile: AgentLevelProfile, level: AgentLevelEntry): HTMLElement {
    const instruction = el("pre", { class: "agent-level-instruction" }, [level.refinedInstruction]);
    const copy = button("Copy prompt", async (event) => {
      const target = event.currentTarget as HTMLButtonElement;
      try {
        await navigator.clipboard.writeText(level.refinedInstruction);
        target.textContent = "Copied";
        window.setTimeout(() => { target.textContent = "Copy prompt"; }, 1200);
      } catch {
        target.textContent = "Copy failed";
      }
    }, { class: "small-btn" });
    return el("article", { class: "agent-level-card" }, [
      el("div", { class: "agent-level-summary" }, [
        el("div", { class: "agent-level-title" }, [
          el("h3", {}, [level.name]),
          el("div", { class: "agent-level-meta" }, [
            el("span", {}, [`Map: ${level.mapId}`]),
            el("span", {}, [`Weather: ${level.weather || "Normal"}`]),
            el("span", {}, [`Tag: ${level.tag || "—"}`]),
          ]),
        ]),
        button("▶ Play", () => this.onPlay(profile, level), { class: "primary agent-play-btn" }),
      ]),
      el("details", { class: "agent-prompt-foldout" }, [
        el("summary", {}, ["Refined instruction to reprompt"]),
        el("div", { class: "agent-prompt-body" }, [instruction, copy]),
      ]),
    ]);
  }
}
